package analysis.arkin;


interface ArkinlabSampleNonCyanos
{
	final static String[] NON_CYANO_HTMLLINES =
	{
		"<LI><A HREF=\"gnc591023.html\">Actinobacillus minor 202</A></LI>",			// NON
		"<LI><A HREF=\"gnc416269.html\">Actinobacillus pleuropneumoniae L20</A></LI>",			// NON
		"<LI><A HREF=\"gnc228399.html\">Actinobacillus pleuropneumoniae serovar 1 str. 4074</A></LI>",			// NON
		"<LI><A HREF=\"gnc434271.html\">Actinobacillus pleuropneumoniae serovar 3 str. JL03</A></LI>",			// NON
		"<LI><A HREF=\"gnc537457.html\">Actinobacillus pleuropneumoniae serovar 7 str. AP76</A></LI>",			// NON
		"<LI><A HREF=\"gnc339671.html\">Actinobacillus succinogenes 130Z</A></LI>",			// NON
		"<LI><A HREF=\"gnc574556.html\">Anaplasma centrale str. Israel</A></LI>",		// NON
		"<LI><A HREF=\"gnc320483.html\">Anaplasma marginale str. Florida</A></LI>",		// NON
		"<LI><A HREF=\"gnc234826.html\">Anaplasma marginale str. St. Maries</A></LI>",		// NON
		"<LI><A HREF=\"gnc212042.html\">Anaplasma phagocytophilum HZ</A></LI>",		// NON
		"<LI><A HREF=\"gnc290340.html\">Arthrobacter aurescens TC1</A></LI>",		// NON
		"<LI><A HREF=\"gnc452863.html\">Arthrobacter chlorophenolicus A6</A></LI>",		// NON
		"<LI><A HREF=\"gnc290399.html\">Arthrobacter sp. FB24</A></LI>",		// NON
		"<LI><A HREF=\"gnc62928.html\">Azoarcus sp. BH72</A></LI>",		// NON
		"<LI><A HREF=\"gnc76114.html\">Azoarcus sp. EbN1</A></LI>",		// NON
		"<LI><A HREF=\"gnc354.html\">Azotobacter vinelandii</A></LI>",		// NON
		"<LI><A HREF=\"gnc322710.html\">Azotobacter vinelandii AvOP</A></LI>",		// NON
		"<LI><A HREF=\"gnc326423.html\">Bacillus amyloliquefaciens FZB42</A></LI>",			// NON
		"<LI><A HREF=\"gnc261594.html\">Bacillus anthracis str. 'Ames Ancestor'</A></LI>",		// NON
		"<LI><A HREF=\"gnc486622.html\">Bacillus anthracis str. A0174</A></LI>",		// NON
		"<LI><A HREF=\"gnc592021.html\">Bacillus anthracis str. A0248</A></LI>",		// NON
		"<LI><A HREF=\"gnc486623.html\">Bacillus anthracis str. A0389</A></LI>",		// NON
		"<LI><A HREF=\"gnc486620.html\">Bacillus anthracis str. A0465</A></LI>",		// NON
		"<LI><A HREF=\"gnc191218.html\">Bacillus anthracis str. A2012</A></LI>",		// NON
		"<LI><A HREF=\"gnc198094.html\">Bacillus anthracis str. Ames</A></LI>",		// NON
		"<LI><A HREF=\"gnc568206.html\">Bacillus anthracis str. CDC 684</A></LI>",		// NON
		"<LI><A HREF=\"gnc260799.html\">Bacillus anthracis str. Sterne</A></LI>",		// NON
		"<LI><A HREF=\"gnc572264.html\">Bacillus cereus 03BB102</A></LI>",		// NON
		"<LI><A HREF=\"gnc405534.html\">Bacillus cereus AH187</A></LI>",		// NON
		"<LI><A HREF=\"gnc405535.html\">Bacillus cereus AH820</A></LI>",		// NON
		"<LI><A HREF=\"gnc222523.html\">Bacillus cereus ATCC 10987</A></LI>",		// NON
		"<LI><A HREF=\"gnc226900.html\">Bacillus cereus ATCC 14579</A></LI>",		// NON
		"<LI><A HREF=\"gnc405532.html\">Bacillus cereus B4264</A></LI>",		// NON
		"<LI><A HREF=\"gnc269801.html\">Bacillus cereus G9241</A></LI>",		// NON
		"<LI><A HREF=\"gnc405531.html\">Bacillus cereus G9842</A></LI>",		// NON
		"<LI><A HREF=\"gnc451708.html\">Bacillus cereus H3081.97</A></LI>",		// NON
		"<LI><A HREF=\"gnc361100.html\">Bacillus cereus Q1</A></LI>",		// NON
		"<LI><A HREF=\"gnc288681.html\">Bacillus cereus ZK</A></LI>",		// NON
		"<LI><A HREF=\"gnc315749.html\">Bacillus cereus subsp. cytotoxis NVH 391-98</A></LI>",		// NON
		"<LI><A HREF=\"gnc66692.html\">Bacillus clausii KSM-K16</A></LI>",		// NON
		"<LI><A HREF=\"gnc345219.html\">Bacillus coagulans 36D1</A></LI>",		// NON
		"<LI><A HREF=\"gnc441769.html\">Bacillus coahuilensis m4-4</A></LI>",		// NON
		"<LI><A HREF=\"gnc272558.html\">Bacillus halodurans C-125</A></LI>",		// NON
		"<LI><A HREF=\"gnc279010.html\">Bacillus licheniformis DSM 13</A></LI>",		// NON
		"<LI><A HREF=\"gnc592022.html\">Bacillus megaterium DSM319</A></LI>",		// NON
		"<LI><A HREF=\"gnc545693.html\">Bacillus megaterium QM B1551</A></LI>",		// NON
		"<LI><A HREF=\"gnc398511.html\">Bacillus pseudofirmus OF4</A></LI>",		// NON
		"<LI><A HREF=\"gnc536229.html\">Bacillus pumilus ATCC 7061</A></LI>",		// NON
		"<LI><A HREF=\"gnc315750.html\">Bacillus pumilus SAFR-032</A></LI>",		// NON
		"<LI><A HREF=\"gnc313627.html\">Bacillus sp. NRRL B-14911</A></LI>",		// NON
		"<LI><A HREF=\"gnc224308.html\">Bacillus subtilis subsp. subtilis str. 168</A></LI>",		// NON
		"<LI><A HREF=\"gnc535025.html\">Bacillus subtilis subsp. subtilis str. JH642</A></LI>",		// NON
		"<LI><A HREF=\"gnc535026.html\">Bacillus subtilis subsp. subtilis str. NCIB 3610</A></LI>",		// NON
		"<LI><A HREF=\"gnc535024.html\">Bacillus subtilis subsp. subtilis str. SMY</A></LI>",		// NON
		"<LI><A HREF=\"gnc339854.html\">Bacillus thuringiensis serovar israelensis ATCC 35646</A></LI>",		// NON
		"<LI><A HREF=\"gnc281309.html\">Bacillus thuringiensis str. 97-27</A></LI>",		// NON
		"<LI><A HREF=\"gnc412694.html\">Bacillus thuringiensis str. Al Hakam</A></LI>",		// NON
		"<LI><A HREF=\"gnc562970.html\">Bacillus tusciae DSM 2912</A></LI>",		// NON
		"<LI><A HREF=\"gnc315730.html\">Bacillus weihenstephanensis KBAB4</A></LI>",		// NON
		"<LI><A HREF=\"gnc537012.html\">Bacteroides cellulosilyticus DSM 14838</A></LI>",		// NON
		"<LI><A HREF=\"gnc547042.html\">Bacteroides coprophilus DSM 18228</A></LI>",		// NON
		"<LI><A HREF=\"gnc483217.html\">Bacteroides dorei DSM 17855</A></LI>",		// NON
		"<LI><A HREF=\"gnc483216.html\">Bacteroides eggerthii DSM 20697</A></LI>",		// NON
		"<LI><A HREF=\"gnc483215.html\">Bacteroides finegoldii DSM 17565</A></LI>",		// NON
		"<LI><A HREF=\"gnc272559.html\">Bacteroides fragilis NCTC 9343</A></LI>",		// NON
		"<LI><A HREF=\"gnc295405.html\">Bacteroides fragilis YCH46</A></LI>",		// NON
		"<LI><A HREF=\"gnc483218.html\">Bacteroides pectinophilus ATCC 43243</A></LI>",		// NON
		"<LI><A HREF=\"gnc484018.html\">Bacteroides plebeius DSM 17135</A></LI>",		// NON
		"<LI><A HREF=\"gnc226186.html\">Bacteroides thetaiotaomicron VPI-5482</A></LI>",		// NON
		"<LI><A HREF=\"gnc435590.html\">Bacteroides vulgatus ATCC 8482</A></LI>",		// NON
		"<LI><A HREF=\"gnc360095.html\">Bartonella bacilliformis KC583</A></LI>",		// NON
		"<LI><A HREF=\"gnc634504.html\">Bartonella grahamii as4aup</A></LI>",		// NON
		"<LI><A HREF=\"gnc283166.html\">Bartonella henselae str. Houston-1</A></LI>",		// NON
		"<LI><A HREF=\"gnc283165.html\">Bartonella quintana str. Toulouse</A></LI>",		// NON
		"<LI><A HREF=\"gnc382640.html\">Bartonella tribocorum CIP 105476</A></LI>",		// NON
		"<LI><A HREF=\"gnc367928.html\">Bifidobacterium adolescentis ATCC 15703</A></LI>",		// NON
		"<LI><A HREF=\"gnc518635.html\">Bifidobacterium angulatum DSM 20098</A></LI>",		// NON
		"<LI><A HREF=\"gnc442563.html\">Bifidobacterium animalis subsp. lactis AD011</A></LI>",		// NON
		"<LI><A HREF=\"gnc580050.html\">Bifidobacterium animalis subsp. lactis Bl-04</A></LI>",		// NON
		"<LI><A HREF=\"gnc555970.html\">Bifidobacterium animalis subsp. lactis DSM 10140</A></LI>",		// NON
		"<LI><A HREF=\"gnc486409.html\">Bifidobacterium animalis subsp. lactis HN019</A></LI>",		// NON
		"<LI><A HREF=\"gnc398513.html\">Bifidobacterium bifidum NCIMB 41171</A></LI>",		// NON
		"<LI><A HREF=\"gnc518634.html\">Bifidobacterium breve DSM 20213</A></LI>",		// NON
		"<LI><A HREF=\"gnc566552.html\">Bifidobacterium catenulatum DSM 16992</A></LI>",		// NON
		"<LI><A HREF=\"gnc401473.html\">Bifidobacterium dentium Bd1</A></LI>",		// NON
		"<LI><A HREF=\"gnc561180.html\">Bifidobacterium gallicum DSM 20093</A></LI>",		// NON
		"<LI><A HREF=\"gnc205913.html\">Bifidobacterium longum DJO10A</A></LI>",		// NON
		"<LI><A HREF=\"gnc206672.html\">Bifidobacterium longum NCC2705</A></LI>",		// NON
		"<LI><A HREF=\"gnc391904.html\">Bifidobacterium longum subsp. infantis ATCC 15697</A></LI>",		// NON
		"<LI><A HREF=\"gnc537937.html\">Bifidobacterium longum subsp. infantis CCUG 52486</A></LI>",		// NON
		"<LI><A HREF=\"gnc360910.html\">Bordetella avium 197N</A></LI>",		// NON
		"<LI><A HREF=\"gnc257310.html\">Bordetella bronchiseptica RB50</A></LI>",		// NON
		"<LI><A HREF=\"gnc257311.html\">Bordetella parapertussis 12822</A></LI>",		// NON
		"<LI><A HREF=\"gnc257313.html\">Bordetella pertussis Tohama I</A></LI>",		// NON
		"<LI><A HREF=\"gnc340100.html\">Bordetella petrii DSM 12804</A></LI>",		// NON
		"<LI><A HREF=\"gnc445986.html\">Borrelia afzelii ACA-1</A></LI>",	// NON
		"<LI><A HREF=\"gnc390236.html\">Borrelia afzelii PKo</A></LI>",	// NON
		"<LI><A HREF=\"gnc476210.html\">Borrelia burgdorferi 118a</A></LI>",	// NON
		"<LI><A HREF=\"gnc445983.html\">Borrelia burgdorferi 156a</A></LI>",	// NON
		"<LI><A HREF=\"gnc498738.html\">Borrelia burgdorferi 29805</A></LI>",	// NON
		"<LI><A HREF=\"gnc476211.html\">Borrelia burgdorferi 72a</A></LI>",	// NON
		"<LI><A HREF=\"gnc476212.html\">Borrelia burgdorferi 94a</A></LI>",	// NON
		"<LI><A HREF=\"gnc224326.html\">Borrelia burgdorferi B31</A></LI>",	// NON
		"<LI><A HREF=\"gnc445984.html\">Borrelia burgdorferi Bol26</A></LI>",	// NON
		"<LI><A HREF=\"gnc445985.html\">Borrelia burgdorferi ZS7</A></LI>",	// NON
		"<LI><A HREF=\"gnc412419.html\">Borrelia duttonii Ly</A></LI>",	// NON
		"<LI><A HREF=\"gnc519049.html\">Borrelia garinii Far04</A></LI>",	// NON
		"<LI><A HREF=\"gnc290434.html\">Borrelia garinii PBi</A></LI>",	// NON
		"<LI><A HREF=\"gnc314723.html\">Borrelia hermsii DAH</A></LI>",	// NON
		"<LI><A HREF=\"gnc412418.html\">Borrelia recurrentis A1</A></LI>",	// NON
		"<LI><A HREF=\"gnc498741.html\">Borrelia sp. SV1</A></LI>",	// NON
		"<LI><A HREF=\"gnc314724.html\">Borrelia turicatae 91E135</A></LI>",	// NON
		"<LI><A HREF=\"gnc445987.html\">Borrelia valaisiana VS116</A></LI>",	// NON
		"<LI><A HREF=\"gnc224911.html\">Bradyrhizobium japonicum USDA 110</A></LI>",		// NON
		"<LI><A HREF=\"gnc288000.html\">Bradyrhizobium sp. BTAi1</A></LI>",		// NON
		"<LI><A HREF=\"gnc114615.html\">Bradyrhizobium sp. ORS278</A></LI>",		// NON
		"<LI><A HREF=\"gnc430066.html\">Brucella abortus S19</A></LI>",	// NON
		"<LI><A HREF=\"gnc262698.html\">Brucella abortus biovar 1 str. 9-941</A></LI>",	// NON
		"<LI><A HREF=\"gnc483179.html\">Brucella canis ATCC 23365</A></LI>",	// NON
		"<LI><A HREF=\"gnc224914.html\">Brucella melitensis 16M</A></LI>",	// NON
		"<LI><A HREF=\"gnc546272.html\">Brucella melitensis ATCC 23457</A></LI>",	// NON
		"<LI><A HREF=\"gnc568815.html\">Brucella microti CCM 4915</A></LI>",	// NON
		"<LI><A HREF=\"gnc444178.html\">Brucella ovis ATCC 25840</A></LI>",	// NON
		"<LI><A HREF=\"gnc204722.html\">Brucella suis 1330</A></LI>",	// NON
		"<LI><A HREF=\"gnc470137.html\">Brucella suis ATCC 23445</A></LI>",	// NON
		"<LI><A HREF=\"gnc563178.html\">Buchnera aphidicola str. 5A (Acyrthosiphon pisum)</A></LI>",		// NON
		"<LI><A HREF=\"gnc107806.html\">Buchnera aphidicola str. APS</A></LI>",		// NON
		"<LI><A HREF=\"gnc224915.html\">Buchnera aphidicola str. Bp</A></LI>",		// NON
		"<LI><A HREF=\"gnc372461.html\">Buchnera aphidicola str. Cc</A></LI>",		// NON
		"<LI><A HREF=\"gnc198804.html\">Buchnera aphidicola str. Sg</A></LI>",		// NON
		"<LI><A HREF=\"gnc561501.html\">Buchnera aphidicola str. Tuc7 (Acyrthosiphon pisum)</A></LI>",		// NON
		"<LI><A HREF=\"gnc396596.html\">Burkholderia ambifaria IOP40-10</A></LI>",	// NON
		"<LI><A HREF=\"gnc398577.html\">Burkholderia ambifaria MC40-6</A></LI>",	// NON
		"<LI><A HREF=\"gnc396597.html\">Burkholderia ambifaria MEX-5</A></LI>",	// NON
		"<LI><A HREF=\"gnc331271.html\">Burkholderia cenocepacia AU 1054</A></LI>",	// NON
		"<LI><A HREF=\"gnc331272.html\">Burkholderia cenocepacia HI2424</A></LI>",	// NON
		"<LI><A HREF=\"gnc216591.html\">Burkholderia cenocepacia J2315</A></LI>",	// NON
		"<LI><A HREF=\"gnc406425.html\">Burkholderia cenocepacia MC0-3</A></LI>",	// NON
		"<LI><A HREF=\"gnc350702.html\">Burkholderia cenocepacia PC184</A></LI>",	// NON
		"<LI><A HREF=\"gnc339670.html\">Burkholderia cepacia AMMD</A></LI>",	// NON
		"<LI><A HREF=\"gnc350701.html\">Burkholderia dolosa AUO158</A></LI>",	// NON
		"<LI><A HREF=\"gnc626418.html\">Burkholderia glumae BGR1</A></LI>",	// NON
		"<LI><A HREF=\"gnc396598.html\">Burkholderia graminis C4D1M</A></LI>",	// NON
		"<LI><A HREF=\"gnc370895.html\">Burkholderia mallei 2002721280</A></LI>",	// NON
		"<LI><A HREF=\"gnc243160.html\">Burkholderia mallei ATCC 23344</A></LI>",	// NON
		"<LI><A HREF=\"gnc334802.html\">Burkholderia mallei FMH</A></LI>",	// NON
		"<LI><A HREF=\"gnc320390.html\">Burkholderia mallei GB8 horse 4</A></LI>",	// NON
		"<LI><A HREF=\"gnc334803.html\">Burkholderia mallei JHU</A></LI>",	// NON
		"<LI><A HREF=\"gnc412022.html\">Burkholderia mallei NCTC 10229</A></LI>",	// NON
		"<LI><A HREF=\"gnc320389.html\">Burkholderia mallei NCTC 10247</A></LI>",	// NON
		"<LI><A HREF=\"gnc320388.html\">Burkholderia mallei SAVP1</A></LI>",	// NON
		"<LI><A HREF=\"gnc395019.html\">Burkholderia multivorans ATCC 17616</A></LI>",	// NON
		"<LI><A HREF=\"gnc513051.html\">Burkholderia multivorans CGD1</A></LI>",	// NON
		"<LI><A HREF=\"gnc513052.html\">Burkholderia multivorans CGD2</A></LI>",	// NON
		"<LI><A HREF=\"gnc513053.html\">Burkholderia multivorans CGD2M</A></LI>",	// NON
		"<LI><A HREF=\"gnc391038.html\">Burkholderia phymatum STM815</A></LI>",	// NON
		"<LI><A HREF=\"gnc398527.html\">Burkholderia phytofirmans PsJN</A></LI>",	// NON
		"<LI><A HREF=\"gnc357348.html\">Burkholderia pseudomallei 1106a</A></LI>",	// NON
		"<LI><A HREF=\"gnc331109.html\">Burkholderia pseudomallei 1655</A></LI>",	// NON
		"<LI><A HREF=\"gnc320372.html\">Burkholderia pseudomallei 1710b</A></LI>",	// NON
		"<LI><A HREF=\"gnc360118.html\">Burkholderia pseudomallei 406e</A></LI>",	// NON
		"<LI><A HREF=\"gnc557724.html\">Burkholderia pseudomallei 576</A></LI>",	// NON
		"<LI><A HREF=\"gnc320373.html\">Burkholderia pseudomallei 668</A></LI>",	// NON
		"<LI><A HREF=\"gnc272560.html\">Burkholderia pseudomallei K96243</A></LI>",	// NON
		"<LI><A HREF=\"gnc536230.html\">Burkholderia pseudomallei MSHR346</A></LI>",	// NON
		"<LI><A HREF=\"gnc331978.html\">Burkholderia pseudomallei Pasteur</A></LI>",	// NON
		"<LI><A HREF=\"gnc320374.html\">Burkholderia pseudomallei S13</A></LI>",	// NON
		"<LI><A HREF=\"gnc269483.html\">Burkholderia sp. 383</A></LI>",	// NON
		"<LI><A HREF=\"gnc640511.html\">Burkholderia sp. CCGE1002</A></LI>",	// NON
		"<LI><A HREF=\"gnc516466.html\">Burkholderia sp. H160</A></LI>",	// NON
		"<LI><A HREF=\"gnc271848.html\">Burkholderia thailandensis E264</A></LI>",	// NON
		"<LI><A HREF=\"gnc269482.html\">Burkholderia vietnamiensis G4</A></LI>",	// NON
		"<LI><A HREF=\"gnc266265.html\">Burkholderia xenovorans LB400</A></LI>",	// NON
		"<LI><A HREF=\"gnc306254.html\">Campylobacter coli RM2228</A></LI>",	// NON
		"<LI><A HREF=\"gnc360104.html\">Campylobacter concisus 13826</A></LI>",	// NON
		"<LI><A HREF=\"gnc360105.html\">Campylobacter curvus 525.92</A></LI>",	// NON
		"<LI><A HREF=\"gnc360106.html\">Campylobacter fetus subsp. fetus 82-40</A></LI>",	// NON
		"<LI><A HREF=\"gnc360107.html\">Campylobacter hominis ATCC BAA-381</A></LI>",	// NON
		"<LI><A HREF=\"gnc195099.html\">Campylobacter jejuni RM1221</A></LI>",	// NON
		"<LI><A HREF=\"gnc360109.html\">Campylobacter jejuni subsp. doylei 269.97</A></LI>",	// NON
		"<LI><A HREF=\"gnc360108.html\">Campylobacter jejuni subsp. jejuni 260.94</A></LI>",	// NON
		"<LI><A HREF=\"gnc354242.html\">Campylobacter jejuni subsp. jejuni 81-176</A></LI>",	// NON
		"<LI><A HREF=\"gnc407148.html\">Campylobacter jejuni subsp. jejuni 81116</A></LI>",	// NON
		"<LI><A HREF=\"gnc360110.html\">Campylobacter jejuni subsp. jejuni 84-25</A></LI>",	// NON
		"<LI><A HREF=\"gnc482628.html\">Campylobacter jejuni subsp. jejuni BH-01-0142</A></LI>",	// NON
		"<LI><A HREF=\"gnc360111.html\">Campylobacter jejuni subsp. jejuni CF93-6</A></LI>",	// NON
		"<LI><A HREF=\"gnc478547.html\">Campylobacter jejuni subsp. jejuni CG8421</A></LI>",	// NON
		"<LI><A HREF=\"gnc360112.html\">Campylobacter jejuni subsp. jejuni HB93-13</A></LI>",	// NON
		"<LI><A HREF=\"gnc192222.html\">Campylobacter jejuni subsp. jejuni NCTC 11168</A></LI>",	// NON
		"<LI><A HREF=\"gnc306263.html\">Campylobacter lari RM2100</A></LI>",	// NON
		"<LI><A HREF=\"gnc553218.html\">Campylobacter rectus RM3267</A></LI>",	// NON
		"<LI><A HREF=\"gnc306264.html\">Campylobacter upsaliensis RM3195</A></LI>",	// NON
		"<LI><A HREF=\"gnc335992.html\">Cand. Pelagibacter ubique HTCC1062</A></LI>",	// NON
		"<LI><A HREF=\"gnc511995.html\">Candidatus Azobacteroides pseudotrichonymphae genomovar. CFP2</A></LI>",	// NON
		"<LI><A HREF=\"gnc641892.html\">Candidatus Sulcia muelleri DMIN</A></LI>",	// NON
		"<LI><A HREF=\"gnc444179.html\">Candidatus Sulcia muelleri GWSS</A></LI>",	// NON
		"<LI><A HREF=\"gnc595499.html\">Candidatus Sulcia muelleri SMDSEM</A></LI>",	// NON
		"<LI><A HREF=\"gnc374675.html\">Candidatus Sulcia muelleri str. Hc (Homalodisca coagulata)</A></LI>",	// NON
		"<LI><A HREF=\"gnc190650.html\">Caulobacter crescentus CB15</A></LI>",	// NON
		"<LI><A HREF=\"gnc565050.html\">Caulobacter crescentus NA1000</A></LI>",	// NON
		"<LI><A HREF=\"gnc509190.html\">Caulobacter segnis ATCC 21756</A></LI>",	// NON
		"<LI><A HREF=\"gnc366602.html\">Caulobacter sp. K31</A></LI>",	// NON
		"<LI><A HREF=\"gnc243161.html\">Chlamydia muridarum Nigg</A></LI>",	// NON
		"<LI><A HREF=\"gnc471472.html\">Chlamydia trachomatis 434/Bu</A></LI>",	// NON
		"<LI><A HREF=\"gnc315277.html\">Chlamydia trachomatis A/HAR-13</A></LI>",	// NON
		"<LI><A HREF=\"gnc580049.html\">Chlamydia trachomatis B/Jali20/OT</A></LI>",	// NON
		"<LI><A HREF=\"gnc672161.html\">Chlamydia trachomatis B/TZ1A828/OT</A></LI>",	// NON
		"<LI><A HREF=\"gnc272561.html\">Chlamydia trachomatis D/UW-3/CX</A></LI>",	// NON
		"<LI><A HREF=\"gnc471473.html\">Chlamydia trachomatis L2b/UCH-1/proctitis</A></LI>",	// NON
		"<LI><A HREF=\"gnc218497.html\">Chlamydophila abortus S26/3</A></LI>",	// NON
		"<LI><A HREF=\"gnc227941.html\">Chlamydophila caviae GPIC</A></LI>",	// NON
		"<LI><A HREF=\"gnc264202.html\">Chlamydophila felis Fe/C-56</A></LI>",	// NON
		"<LI><A HREF=\"gnc115711.html\">Chlamydophila pneumoniae AR39</A></LI>",	// NON
		"<LI><A HREF=\"gnc115713.html\">Chlamydophila pneumoniae CWL029</A></LI>",	// NON
		"<LI><A HREF=\"gnc138677.html\">Chlamydophila pneumoniae J138</A></LI>",	// NON
		"<LI><A HREF=\"gnc182082.html\">Chlamydophila pneumoniae TW-183</A></LI>",	// NON
		"<LI><A HREF=\"gnc340177.html\">Chlorobium chlorochromatii CaD3</A></LI>",	// NON
		"<LI><A HREF=\"gnc377431.html\">Chlorobium ferrooxidans DSM 13031</A></LI>",	// NON
		"<LI><A HREF=\"gnc290315.html\">Chlorobium limicola DSM 245</A></LI>",	// NON
		"<LI><A HREF=\"gnc331678.html\">Chlorobium phaeobacteroides BS1</A></LI>",	// NON
		"<LI><A HREF=\"gnc290317.html\">Chlorobium phaeobacteroides DSM 266</A></LI>",	// NON
		"<LI><A HREF=\"gnc194439.html\">Chlorobium tepidum TLS</A></LI>",	// NON
		"<LI><A HREF=\"gnc326427.html\">Chloroflexus aggregans DSM 9485</A></LI>",	// NON
		"<LI><A HREF=\"gnc324602.html\">Chloroflexus aurantiacus J-10-fl</A></LI>",	// NON
		"<LI><A HREF=\"gnc480224.html\">Chloroflexus sp. Y-400-fl</A></LI>",	// NON
		"<LI><A HREF=\"gnc290402.html\">Clostridium beijerincki NCIMB 8052</A></LI>",	// NON
		"<LI><A HREF=\"gnc441770.html\">Clostridium botulinum A str. ATCC 19397</A></LI>",	// NON
		"<LI><A HREF=\"gnc413999.html\">Clostridium botulinum A str. ATCC 3502</A></LI>",	// NON
		"<LI><A HREF=\"gnc441771.html\">Clostridium botulinum A str. Hall</A></LI>",	// NON
		"<LI><A HREF=\"gnc536232.html\">Clostridium botulinum A2 str. Kyoto</A></LI>",	// NON
		"<LI><A HREF=\"gnc498214.html\">Clostridium botulinum A3 str. Loch Maree</A></LI>",	// NON
		"<LI><A HREF=\"gnc508765.html\">Clostridium botulinum B str. Eklund 17B</A></LI>",	// NON
		"<LI><A HREF=\"gnc498213.html\">Clostridium botulinum B1 str. Okra</A></LI>",	// NON
		"<LI><A HREF=\"gnc515621.html\">Clostridium botulinum Ba4 str. 657</A></LI>",	// NON
		"<LI><A HREF=\"gnc508767.html\">Clostridium botulinum E3 str. Alaska E43</A></LI>",	// NON
		"<LI><A HREF=\"gnc441772.html\">Clostridium botulinum F str. Langeland</A></LI>",	// NON
		"<LI><A HREF=\"gnc447214.html\">Clostridium butyricum 5521</A></LI>",	// NON
		"<LI><A HREF=\"gnc394503.html\">Clostridium cellulolyticum H10</A></LI>",	// NON
		"<LI><A HREF=\"gnc272563.html\">Clostridium difficile 630</A></LI>",	// NON
		"<LI><A HREF=\"gnc645462.html\">Clostridium difficile CD196</A></LI>",	// NON
		"<LI><A HREF=\"gnc645463.html\">Clostridium difficile R20291</A></LI>",	// NON
		"<LI><A HREF=\"gnc500633.html\">Clostridium hiranonis DSM 13275</A></LI>",	// NON
		"<LI><A HREF=\"gnc431943.html\">Clostridium kluyveri DSM 555</A></LI>",	// NON
		"<LI><A HREF=\"gnc583346.html\">Clostridium kluyveri NBRC 12016</A></LI>",	// NON
		"<LI><A HREF=\"gnc500632.html\">Clostridium nexile DSM 1787</A></LI>",	// NON
		"<LI><A HREF=\"gnc386415.html\">Clostridium novyi NT</A></LI>",	// NON
		"<LI><A HREF=\"gnc195103.html\">Clostridium perfringens ATCC 13124</A></LI>",	// NON
		"<LI><A HREF=\"gnc451756.html\">Clostridium perfringens CPE str. F4969</A></LI>",	// NON
		"<LI><A HREF=\"gnc488537.html\">Clostridium perfringens D str. JGS1721</A></LI>",	// NON
		"<LI><A HREF=\"gnc289380.html\">Clostridium perfringens SM101</A></LI>",	// NON
		"<LI><A HREF=\"gnc195102.html\">Clostridium perfringens str. 13</A></LI>",	// NON
		"<LI><A HREF=\"gnc357809.html\">Clostridium phytofermentans ISDg</A></LI>",	// NON
		"<LI><A HREF=\"gnc350688.html\">Clostridium sp. OhILAs</A></LI>",	// NON
		"<LI><A HREF=\"gnc471871.html\">Clostridium sporogenes ATCC 15579</A></LI>",	// NON
		"<LI><A HREF=\"gnc212717.html\">Clostridium tetani E88</A></LI>",	// NON
		"<LI><A HREF=\"gnc203119.html\">Clostridium thermocellum ATCC 27405</A></LI>",	// NON
		"<LI><A HREF=\"gnc492476.html\">Clostridium thermocellum DSM 4150</A></LI>",	// NON
		"<LI><A HREF=\"gnc553204.html\">Corynebacterium amycolatum SK46</A></LI>",	// NON
		"<LI><A HREF=\"gnc548476.html\">Corynebacterium aurimucosum ATCC 700975</A></LI>",	// NON
		"<LI><A HREF=\"gnc257309.html\">Corynebacterium diphtheriae NCTC 13129</A></LI>",	// NON
		"<LI><A HREF=\"gnc196164.html\">Corynebacterium efficiens YS-314</A></LI>",	// NON
		"<LI><A HREF=\"gnc196627.html\">Corynebacterium glutamicum</A></LI>",	// NON
		"<LI><A HREF=\"gnc340322.html\">Corynebacterium glutamicum R</A></LI>",	// NON
		"<LI><A HREF=\"gnc306537.html\">Corynebacterium jeikeium K411</A></LI>",	// NON
		"<LI><A HREF=\"gnc645127.html\">Corynebacterium kroppenstedtii DSM 44385</A></LI>",	// NON
		"<LI><A HREF=\"gnc504474.html\">Corynebacterium urealyticum DSM 7109</A></LI>",	// NON
		"<LI><A HREF=\"gnc434923.html\">Coxiella burnetii CbuG_Q212</A></LI>",	// NON
		"<LI><A HREF=\"gnc434924.html\">Coxiella burnetii CbuK_Q154</A></LI>",	// NON
		"<LI><A HREF=\"gnc434922.html\">Coxiella burnetii Dugway 5J108-111</A></LI>",	// NON
		"<LI><A HREF=\"gnc360115.html\">Coxiella burnetii RSA 331</A></LI>",	// NON
		"<LI><A HREF=\"gnc227377.html\">Coxiella burnetii RSA 493</A></LI>",	// NON
		"<LI><A HREF=\"gnc243164.html\">Dehalococcoides ethenogenes 195</A></LI>",	// NON
		"<LI><A HREF=\"gnc216389.html\">Dehalococcoides sp. BAV1</A></LI>",	// NON
		"<LI><A HREF=\"gnc255470.html\">Dehalococcoides sp. CBDB1</A></LI>",	// NON
		"<LI><A HREF=\"gnc633145.html\">Dehalococcoides sp. GT</A></LI>",	// NON
		"<LI><A HREF=\"gnc439235.html\">Desulfatibacillum alkenivorans AK-01</A></LI>",	// NON
		"<LI><A HREF=\"gnc272564.html\">Desulfitobacterium hafniense DCB-2</A></LI>",	// NON
		"<LI><A HREF=\"gnc138119.html\">Desulfitobacterium hafniense Y51</A></LI>",	// NON
		"<LI><A HREF=\"gnc177437.html\">Desulfobacterium autotrophicum HRM2</A></LI>",	// NON
		"<LI><A HREF=\"gnc485915.html\">Desulfohalobium retbaense DSM 5692</A></LI>",	// NON
		"<LI><A HREF=\"gnc525897.html\">Desulfomicrobium baculatum DSM 4028</A></LI>",	// NON
		"<LI><A HREF=\"gnc477974.html\">Desulforudis audaxviator MP104C</A></LI>",	// NON
		"<LI><A HREF=\"gnc177439.html\">Desulfotalea psychrophila LSv54</A></LI>",	// NON
		"<LI><A HREF=\"gnc485916.html\">Desulfotomaculum acetoxidans DSM 771</A></LI>",	// NON
		"<LI><A HREF=\"gnc349161.html\">Desulfotomaculum reducens MI-1</A></LI>",	// NON
		"<LI><A HREF=\"gnc207559.html\">Desulfovibrio desulfuricans G20</A></LI>",	// NON
		"<LI><A HREF=\"gnc573370.html\">Desulfovibrio magneticus RS-1</A></LI>",	// NON
		"<LI><A HREF=\"gnc411464.html\">Desulfovibrio piger ATCC 29098</A></LI>",	// NON
		"<LI><A HREF=\"gnc391774.html\">Desulfovibrio vulgaris DP4</A></LI>",	// NON
		"<LI><A HREF=\"gnc882.html\">Desulfovibrio vulgaris Hildenborough</A></LI>",	// NON
		"<LI><A HREF=\"gnc490899.html\">Desulfurococcus kamchatkensis 1221n</A></LI>",	// NON
		"<LI><A HREF=\"gnc281689.html\">Desulfuromonas acetoxidans DSM 684</A></LI>",	// NON
		"<LI><A HREF=\"gnc891.html\">Desulfuromonas spp.</A></LI>",	// NON
		"<LI><A HREF=\"gnc269484.html\">Ehrlichia canis str. Jake</A></LI>",	// NON
		"<LI><A HREF=\"gnc205920.html\">Ehrlichia chaffeensis str. Arkansas</A></LI>",	// NON
		"<LI><A HREF=\"gnc332415.html\">Ehrlichia chaffeensis str. Sapulpa</A></LI>",	// NON
		"<LI><A HREF=\"gnc302409.html\">Ehrlichia ruminantium str. Gardel</A></LI>",	// NON
		"<LI><A HREF=\"gnc254945.html\">Ehrlichia ruminantium str. Welgevonden</A></LI>",	// NON
		"<LI><A HREF=\"gnc500639.html\">Enterobacter cancerogenus ATCC 35316</A></LI>",				// NON2
		"<LI><A HREF=\"gnc716541.html\">Enterobacter cloacae subsp. cloacae ATCC 13047</A></LI>",				// NON2
		"<LI><A HREF=\"gnc290339.html\">Enterobacter sakazakii ATCC BAA-894</A></LI>",				// NON2
		"<LI><A HREF=\"gnc399742.html\">Enterobacter sp. 638</A></LI>",				// NON2
		"<LI><A HREF=\"gnc474186.html\">Enterococcus faecalis OG1RF</A></LI>",				// NON2
		"<LI><A HREF=\"gnc226185.html\">Enterococcus faecalis V583</A></LI>",				// NON2
		"<LI><A HREF=\"gnc333849.html\">Enterococcus faecium DO</A></LI>",				// NON2
		"<LI><A HREF=\"gnc716540.html\">Erwinia amylovora ATCC 49946</A></LI>",		// NON2
		"<LI><A HREF=\"gnc665029.html\">Erwinia amylovora CFBP1430</A></LI>",		// NON2
		"<LI><A HREF=\"gnc218491.html\">Erwinia carotovora, SCRI1043</A></LI>",		// NON2
		"<LI><A HREF=\"gnc634499.html\">Erwinia pyrifoliae Ep1/96</A></LI>",		// NON2
		"<LI><A HREF=\"gnc465817.html\">Erwinia tasmaniensis Et1/99</A></LI>",		// NON2
		"<LI><A HREF=\"gnc314225.html\">Erythrobacter litoralis HTCC2594</A></LI>",		// NON2
		"<LI><A HREF=\"gnc237727.html\">Erythrobacter sp. NAP1</A></LI>",		// NON2
		"<LI><A HREF=\"gnc866768.html\">Escherichia coli 'BL21-Gold(DE3)pLysS AG'</A></LI>",          // NON
		"<LI><A HREF=\"gnc358709.html\">Escherichia coli 101-1</A></LI>",          // NON
		"<LI><A HREF=\"gnc362663.html\">Escherichia coli 536</A></LI>",          // NON
		"<LI><A HREF=\"gnc344610.html\">Escherichia coli 53638</A></LI>",          // NON
		"<LI><A HREF=\"gnc585055.html\">Escherichia coli 55989</A></LI>",          // NON
		"<LI><A HREF=\"gnc405955.html\">Escherichia coli APEC O1</A></LI>",          // NON
		"<LI><A HREF=\"gnc37762.html\">Escherichia coli B</A></LI>",          // NON
		"<LI><A HREF=\"gnc413997.html\">Escherichia coli B str. REL606</A></LI>",          // NON
		"<LI><A HREF=\"gnc344601.html\">Escherichia coli B171</A></LI>",          // NON
		"<LI><A HREF=\"gnc340184.html\">Escherichia coli B7A</A></LI>",          // NON
		"<LI><A HREF=\"gnc595496.html\">Escherichia coli BW2952</A></LI>",          // NON
		"<LI><A HREF=\"gnc481805.html\">Escherichia coli C str. ATCC 8739</A></LI>",          // NON
		"<LI><A HREF=\"gnc199310.html\">Escherichia coli CFT073</A></LI>",          // NON
		"<LI><A HREF=\"gnc340186.html\">Escherichia coli E110019</A></LI>",          // NON
		"<LI><A HREF=\"gnc340185.html\">Escherichia coli E22</A></LI>",          // NON
		"<LI><A HREF=\"gnc331111.html\">Escherichia coli E24377A</A></LI>",          // NON
		"<LI><A HREF=\"gnc585397.html\">Escherichia coli ED1a</A></LI>",          // NON
		"<LI><A HREF=\"gnc340197.html\">Escherichia coli F11</A></LI>",          // NON
		"<LI><A HREF=\"gnc331112.html\">Escherichia coli HS</A></LI>",          // NON
		"<LI><A HREF=\"gnc585034.html\">Escherichia coli IAI1</A></LI>",          // NON
		"<LI><A HREF=\"gnc585057.html\">Escherichia coli IAI39</A></LI>",          // NON
		"<LI><A HREF=\"gnc585395.html\">Escherichia coli O103:H2 str. 12009</A></LI>",          // NON
		"<LI><A HREF=\"gnc585396.html\">Escherichia coli O111:H- str. 11128</A></LI>",          // NON
		"<LI><A HREF=\"gnc574521.html\">Escherichia coli O127:H6 str. E2348/69</A></LI>",          // NON
		"<LI><A HREF=\"gnc155864.html\">Escherichia coli O157:H7 EDL933</A></LI>",          // NON
		"<LI><A HREF=\"gnc444450.html\">Escherichia coli O157:H7 str. EC4115</A></LI>",          // NON
		"<LI><A HREF=\"gnc386585.html\">Escherichia coli O157:H7 str. Sakai</A></LI>",          // NON
		"<LI><A HREF=\"gnc544404.html\">Escherichia coli O157:H7 str. TW14359</A></LI>",          // NON
		"<LI><A HREF=\"gnc573235.html\">Escherichia coli O26:H11 str. 11368</A></LI>",          // NON
		"<LI><A HREF=\"gnc701177.html\">Escherichia coli O55:H7 str. CB9615</A></LI>",          // NON
		"<LI><A HREF=\"gnc585035.html\">Escherichia coli S88</A></LI>",          // NON
		"<LI><A HREF=\"gnc409438.html\">Escherichia coli SE11</A></LI>",          // NON
		"<LI><A HREF=\"gnc439855.html\">Escherichia coli SECEC SMS-3-5</A></LI>",          // NON
		"<LI><A HREF=\"gnc585056.html\">Escherichia coli UMN026</A></LI>",          // NON
		"<LI><A HREF=\"gnc364106.html\">Escherichia coli UTI89</A></LI>",          // NON
		"<LI><A HREF=\"gnc316407.html\">Escherichia coli W3110</A></LI>",          // NON
		"<LI><A HREF=\"gnc316385.html\">Escherichia coli str. K-12 substr. DH10B</A></LI>",          // NON
		"<LI><A HREF=\"gnc511145.html\">Escherichia coli str. K-12 substr. MG1655</A></LI>",          // NON
		"<LI><A HREF=\"gnc585054.html\">Escherichia fergusonii ATCC 35469</A></LI>",         // NON
		"<LI><A HREF=\"gnc518637.html\">Eubacterium biforme DSM 3989</A></LI>",         // NON
		"<LI><A HREF=\"gnc515620.html\">Eubacterium eligens ATCC 27750</A></LI>",         // NON
		"<LI><A HREF=\"gnc515619.html\">Eubacterium rectale ATCC 33656</A></LI>",         // NON
		"<LI><A HREF=\"gnc262543.html\">Exiguobacterium sibiricum 255-15</A></LI>",        // NON
		"<LI><A HREF=\"gnc360911.html\">Exiguobacterium sp. AT1b</A></LI>",        // NON
		"<LI><A HREF=\"gnc156586.html\">Flavobacteria bacterium BBFL7</A></LI>",	// NON
		"<LI><A HREF=\"gnc531844.html\">Flavobacteriaceae bacterium 3519-10</A></LI>",	// NON
		"<LI><A HREF=\"gnc313603.html\">Flavobacteriales bacterium HTCC2170</A></LI>",	// NON
		"<LI><A HREF=\"gnc376686.html\">Flavobacterium johnsoniae UW101</A></LI>",	// NON
		"<LI><A HREF=\"gnc402612.html\">Flavobacterium psychrophilum JIP02/86</A></LI>",	// NON
		"<LI><A HREF=\"gnc545422.html\">Francisella novicida FTE</A></LI>",        // NON
		"<LI><A HREF=\"gnc563990.html\">Francisella novicida FTG</A></LI>",        // NON
		"<LI><A HREF=\"gnc484022.html\">Francisella philomiragia subsp. philomiragia ATCC 25017</A></LI>",        // NON
		"<LI><A HREF=\"gnc119857.html\">Francisella tularensis holarctica</A></LI>",        // NON
		"<LI><A HREF=\"gnc393011.html\">Francisella tularensis holarctica OSU18</A></LI>",        // NON
		"<LI><A HREF=\"gnc458234.html\">Francisella tularensis subsp. holarctica FTA</A></LI>",        // NON
		"<LI><A HREF=\"gnc441952.html\">Francisella tularensis subsp. mediasiatica FSC147</A></LI>",        // NON
		"<LI><A HREF=\"gnc401614.html\">Francisella tularensis subsp. novicida U112</A></LI>",        // NON
		"<LI><A HREF=\"gnc543737.html\">Francisella tularensis subsp. tularensis MA00-2987</A></LI>",        // NON
		"<LI><A HREF=\"gnc177416.html\">Francisella tularensis subsp. tularensis SCHU S4</A></LI>",        // NON
		"<LI><A HREF=\"gnc418136.html\">Francisella tularensis subsp. tularensis WY96-3418</A></LI>",        // NON
		"<LI><A HREF=\"gnc393115.html\">Francisella tularensis tular. FSC 198</A></LI>",        // NON
		"<LI><A HREF=\"gnc235909.html\">Geobacillus kaustophilus HTA426</A></LI>",        // NON
		"<LI><A HREF=\"gnc495036.html\">Geobacillus sp. G11MC16</A></LI>",        // NON
		"<LI><A HREF=\"gnc471223.html\">Geobacillus sp. WCH70</A></LI>",        // NON
		"<LI><A HREF=\"gnc481743.html\">Geobacillus sp. Y412MC10</A></LI>",        // NON
		"<LI><A HREF=\"gnc544556.html\">Geobacillus sp. Y412MC61</A></LI>",        // NON
		"<LI><A HREF=\"gnc420246.html\">Geobacillus thermodenitrificans NG80-2</A></LI>",        // NON
		"<LI><A HREF=\"gnc404380.html\">Geobacter bemidjiensis Bem</A></LI>",        // NON
		"<LI><A HREF=\"gnc398767.html\">Geobacter lovleyi SZ</A></LI>",        // NON
		"<LI><A HREF=\"gnc269799.html\">Geobacter metallireducens GS-15</A></LI>",        // NON
		"<LI><A HREF=\"gnc316067.html\">Geobacter sp. FRC-32</A></LI>",        // NON
		"<LI><A HREF=\"gnc443144.html\">Geobacter sp. M21</A></LI>",        // NON
		"<LI><A HREF=\"gnc243231.html\">Geobacter sulfurreducens PCA</A></LI>",        // NON
		"<LI><A HREF=\"gnc351605.html\">Geobacter uraniumreducens Rf4</A></LI>",        // NON
		"<LI><A HREF=\"gnc233412.html\">Haemophilus ducreyi 35000HP</A></LI>",          // NON
		"<LI><A HREF=\"gnc281310.html\">Haemophilus influenzae 86-028NP</A></LI>",          // NON
		"<LI><A HREF=\"gnc374930.html\">Haemophilus influenzae PittEE</A></LI>",          // NON
		"<LI><A HREF=\"gnc374931.html\">Haemophilus influenzae PittGG</A></LI>",          // NON
		"<LI><A HREF=\"gnc262727.html\">Haemophilus influenzae R2846</A></LI>",          // NON
		"<LI><A HREF=\"gnc262728.html\">Haemophilus influenzae R2866</A></LI>",          // NON
		"<LI><A HREF=\"gnc71421.html\">Haemophilus influenzae Rd KW20</A></LI>",          // NON
		"<LI><A HREF=\"gnc557723.html\">Haemophilus parasuis SH0165</A></LI>",          // NON
		"<LI><A HREF=\"gnc205914.html\">Haemophilus somnus 129PT</A></LI>",          // NON
		"<LI><A HREF=\"gnc228400.html\">Haemophilus somnus 2336</A></LI>",          // NON
		"<LI><A HREF=\"gnc382638.html\">Helicobacter acinonychis str. Sheeba</A></LI>",          // NON
		"<LI><A HREF=\"gnc537970.html\">Helicobacter canadensis MIT 98-5491</A></LI>",          // NON
		"<LI><A HREF=\"gnc537971.html\">Helicobacter cinaedi CCUG 18818</A></LI>",          // NON
		"<LI><A HREF=\"gnc235279.html\">Helicobacter hepaticus ATCC 51449</A></LI>",          // NON
		"<LI><A HREF=\"gnc679897.html\">Helicobacter mustelae 12198</A></LI>",          // NON
		"<LI><A HREF=\"gnc537972.html\">Helicobacter pullorum MIT 98-5489</A></LI>",          // NON
		"<LI><A HREF=\"gnc85962.html\">Helicobacter pylori 26695</A></LI>",          // NON
		"<LI><A HREF=\"gnc544405.html\">Helicobacter pylori 98-10</A></LI>",          // NON
		"<LI><A HREF=\"gnc544406.html\">Helicobacter pylori B128</A></LI>",          // NON
		"<LI><A HREF=\"gnc592205.html\">Helicobacter pylori B38</A></LI>",          // NON
		"<LI><A HREF=\"gnc563041.html\">Helicobacter pylori G27</A></LI>",          // NON
		"<LI><A HREF=\"gnc357544.html\">Helicobacter pylori HPAG1</A></LI>",          // NON
		"<LI><A HREF=\"gnc499171.html\">Helicobacter pylori HPKX_438_AG0C1</A></LI>",          // NON
		"<LI><A HREF=\"gnc499172.html\">Helicobacter pylori HPKX_438_CA4C1</A></LI>",          // NON
		"<LI><A HREF=\"gnc85963.html\">Helicobacter pylori J99</A></LI>",          // NON
		"<LI><A HREF=\"gnc570508.html\">Helicobacter pylori P12</A></LI>",          // NON
		"<LI><A HREF=\"gnc512562.html\">Helicobacter pylori Shi470</A></LI>",          // NON
		"<LI><A HREF=\"gnc523791.html\">Kangiella koreensis DSM 16069</A></LI>",		// NON2
		"<LI><A HREF=\"gnc507522.html\">Klebsiella pneumoniae 342</A></LI>",		// NON2
		"<LI><A HREF=\"gnc484021.html\">Klebsiella pneumoniae NTUH-K2044</A></LI>",		// NON2
		"<LI><A HREF=\"gnc272620.html\">Klebsiella pneumoniae subsp. pneumoniae MGH 78578</A></LI>",		// NON2
		"<LI><A HREF=\"gnc640131.html\">Klebsiella variicola At-22</A></LI>",		// NON2
		"<LI><A HREF=\"gnc272621.html\">Lactobacillus acidophilus NCFM</A></LI>",          // NON
		"<LI><A HREF=\"gnc387344.html\">Lactobacillus brevis ATCC 367</A></LI>",          // NON
		"<LI><A HREF=\"gnc321967.html\">Lactobacillus casei ATCC 334</A></LI>",          // NON
		"<LI><A HREF=\"gnc543734.html\">Lactobacillus casei BL23</A></LI>",          // NON
		"<LI><A HREF=\"gnc748671.html\">Lactobacillus crispatus ST1</A></LI>",          // NON
		"<LI><A HREF=\"gnc390333.html\">Lactobacillus delbrueckii bulg. 11842</A></LI>",          // NON
		"<LI><A HREF=\"gnc321956.html\">Lactobacillus delbrueckii bulg. BAA-365</A></LI>",          // NON
		"<LI><A HREF=\"gnc334390.html\">Lactobacillus fermentum IFO 3956</A></LI>",          // NON
		"<LI><A HREF=\"gnc324831.html\">Lactobacillus gasseri ATCC 33323</A></LI>",          // NON
		"<LI><A HREF=\"gnc405566.html\">Lactobacillus helveticus DPC 4571</A></LI>",          // NON
		"<LI><A HREF=\"gnc633699.html\">Lactobacillus johnsonii FI9785</A></LI>",          // NON
		"<LI><A HREF=\"gnc257314.html\">Lactobacillus johnsonii NCC 533</A></LI>",          // NON
		"<LI><A HREF=\"gnc537973.html\">Lactobacillus paracasei subsp. paracasei 8700:2</A></LI>",          // NON
		"<LI><A HREF=\"gnc644042.html\">Lactobacillus plantarum JDM1</A></LI>",          // NON
		"<LI><A HREF=\"gnc220668.html\">Lactobacillus plantarum WCFS1</A></LI>",          // NON
		"<LI><A HREF=\"gnc349123.html\">Lactobacillus reuteri 100-23</A></LI>",          // NON
		"<LI><A HREF=\"gnc557436.html\">Lactobacillus reuteri DSM 20016</A></LI>",          // NON
		"<LI><A HREF=\"gnc557433.html\">Lactobacillus reuteri JCM 1112</A></LI>",          // NON
		"<LI><A HREF=\"gnc568703.html\">Lactobacillus rhamnosus GG</A></LI>",          // NON
		"<LI><A HREF=\"gnc486408.html\">Lactobacillus rhamnosus HN001</A></LI>",          // NON
		"<LI><A HREF=\"gnc568704.html\">Lactobacillus rhamnosus Lc 705</A></LI>",          // NON
		"<LI><A HREF=\"gnc314315.html\">Lactobacillus sakei subsp. sakei 23K</A></LI>",          // NON
		"<LI><A HREF=\"gnc362948.html\">Lactobacillus salivarius saliv. UCC118</A></LI>",          // NON
		"<LI><A HREF=\"gnc272622.html\">Lactococcus lactis cremoris SK11</A></LI>",          // NON
		"<LI><A HREF=\"gnc416870.html\">Lactococcus lactis subsp. cremoris MG1363</A></LI>",          // NON
		"<LI><A HREF=\"gnc272623.html\">Lactococcus lactis subsp. lactis Il1403</A></LI>",          // NON
		"<LI><A HREF=\"gnc684738.html\">Lactococcus lactis subsp. lactis KF147</A></LI>",          // NON
		"<LI><A HREF=\"gnc661367.html\">Legionella longbeachae NSW150</A></LI>",         // NON
		"<LI><A HREF=\"gnc272624.html\">Legionella pneumophila str Phil. 1</A></LI>",         // NON
		"<LI><A HREF=\"gnc400673.html\">Legionella pneumophila str. Corby</A></LI>",         // NON
		"<LI><A HREF=\"gnc297245.html\">Legionella pneumophila str. Lens</A></LI>",         // NON
		"<LI><A HREF=\"gnc297246.html\">Legionella pneumophila str. Paris</A></LI>",         // NON
		"<LI><A HREF=\"gnc355278.html\">Leptospira biflexa serovar Patoc strain 'Patoc 1 (Ames)'</A></LI>",         // NON
		"<LI><A HREF=\"gnc456481.html\">Leptospira biflexa serovar Patoc strain 'Patoc 1 (Paris)'</A></LI>",         // NON
		"<LI><A HREF=\"gnc355277.html\">Leptospira borgpetersenii H-b JB197</A></LI>",         // NON
		"<LI><A HREF=\"gnc355276.html\">Leptospira borgpetersenii H-b L550</A></LI>",         // NON
		"<LI><A HREF=\"gnc189518.html\">Leptospira interrogans, 56601</A></LI>",         // NON
		"<LI><A HREF=\"gnc267671.html\">Leptospira interrogans, L1-130</A></LI>",         // NON
		"<LI><A HREF=\"gnc272626.html\">Listeria innocua Clip11262</A></LI>",          // NON
		"<LI><A HREF=\"gnc653938.html\">Listeria monocytogenes 08-5578</A></LI>",          // NON
		"<LI><A HREF=\"gnc637381.html\">Listeria monocytogenes 08-5923</A></LI>",          // NON
		"<LI><A HREF=\"gnc169963.html\">Listeria monocytogenes EGD-e</A></LI>",          // NON
		"<LI><A HREF=\"gnc393126.html\">Listeria monocytogenes FSL R2-561</A></LI>",          // NON
		"<LI><A HREF=\"gnc393127.html\">Listeria monocytogenes Finland 1988</A></LI>",          // NON
		"<LI><A HREF=\"gnc552536.html\">Listeria monocytogenes HCC23</A></LI>",          // NON
		"<LI><A HREF=\"gnc568819.html\">Listeria monocytogenes serotype 4b str. CLIP 80459</A></LI>",          // NON
		"<LI><A HREF=\"gnc267409.html\">Listeria monocytogenes str. 1/2a F6854</A></LI>",          // NON
		"<LI><A HREF=\"gnc265669.html\">Listeria monocytogenes str. 4b F2365</A></LI>",          // NON
		"<LI><A HREF=\"gnc267410.html\">Listeria monocytogenes str. 4b H7858</A></LI>",          // NON
		"<LI><A HREF=\"gnc683837.html\">Listeria seeligeri serovar 1/2b str. SLCC3954</A></LI>",          // NON
		"<LI><A HREF=\"gnc386043.html\">Listeria welshimeri serovar 6b SLCC5334</A></LI>",          // NON
		"<LI><A HREF=\"gnc573064.html\">Methanocaldococcus fervens AG86</A></LI>",				// NON
		"<LI><A HREF=\"gnc243232.html\">Methanocaldococcus jannaschii DSM 2661</A></LI>",				// NON
		"<LI><A HREF=\"gnc644281.html\">Methanocaldococcus sp. FS406-22</A></LI>",				// NON
		"<LI><A HREF=\"gnc579137.html\">Methanocaldococcus vulcanius M7</A></LI>",				// NON
		"<LI><A HREF=\"gnc419665.html\">Methanococcus aeolicus Nankai-3</A></LI>",				// NON
		"<LI><A HREF=\"gnc402880.html\">Methanococcus maripaludis C5</A></LI>",				// NON
		"<LI><A HREF=\"gnc444158.html\">Methanococcus maripaludis C6</A></LI>",				// NON
		"<LI><A HREF=\"gnc426368.html\">Methanococcus maripaludis C7</A></LI>",				// NON
		"<LI><A HREF=\"gnc267377.html\">Methanococcus maripaludis S2</A></LI>",				// NON
		"<LI><A HREF=\"gnc406327.html\">Methanococcus vannielii SB</A></LI>",				// NON
		"<LI><A HREF=\"gnc188937.html\">Methanosarcina acetivorans C2A</A></LI>",				// NON
		"<LI><A HREF=\"gnc269797.html\">Methanosarcina barkeri str. fusaro</A></LI>",				// NON
		"<LI><A HREF=\"gnc192952.html\">Methanosarcina mazei Goe1</A></LI>",				// NON
		"<LI><A HREF=\"gnc187420.html\">Methanothermobacter thermautotrophicus str. Delta H</A></LI>",				// NON
		"<LI><A HREF=\"gnc440085.html\">Methylobacterium chloromethanicum CM4</A></LI>",				// NON
		"<LI><A HREF=\"gnc272630.html\">Methylobacterium extorquens AM1</A></LI>",				// NON
		"<LI><A HREF=\"gnc661410.html\">Methylobacterium extorquens DM4</A></LI>",				// NON
		"<LI><A HREF=\"gnc419610.html\">Methylobacterium extorquens PA1</A></LI>",				// NON
		"<LI><A HREF=\"gnc460265.html\">Methylobacterium nodulans ORS 2060</A></LI>",				// NON
		"<LI><A HREF=\"gnc441620.html\">Methylobacterium populi BJ001</A></LI>",				// NON
		"<LI><A HREF=\"gnc426355.html\">Methylobacterium radiotolerans JCM 2831</A></LI>",				// NON
		"<LI><A HREF=\"gnc426117.html\">Methylobacterium sp. 4-46</A></LI>",				// NON
		"<LI><A HREF=\"gnc561007.html\">Mycobacterium abscessus ATCC 19977</A></LI>",          // NON
		"<LI><A HREF=\"gnc243243.html\">Mycobacterium avium 104</A></LI>",          // NON
		"<LI><A HREF=\"gnc262316.html\">Mycobacterium avium str. k10</A></LI>",          // NON
		"<LI><A HREF=\"gnc233413.html\">Mycobacterium bovis AF2122/97</A></LI>",          // NON
		"<LI><A HREF=\"gnc410289.html\">Mycobacterium bovis BCG str. Pasteur 1173P2</A></LI>",          // NON
		"<LI><A HREF=\"gnc561275.html\">Mycobacterium bovis BCG str. Tokyo 172</A></LI>",          // NON
		"<LI><A HREF=\"gnc350054.html\">Mycobacterium flavescens PYR-GCK</A></LI>",          // NON
		"<LI><A HREF=\"gnc561304.html\">Mycobacterium leprae Br4923</A></LI>",          // NON
		"<LI><A HREF=\"gnc272631.html\">Mycobacterium leprae TN</A></LI>",          // NON
		"<LI><A HREF=\"gnc216594.html\">Mycobacterium marinum M</A></LI>",          // NON
		"<LI><A HREF=\"gnc246196.html\">Mycobacterium smegmatis str. MC2 155</A></LI>",          // NON
		"<LI><A HREF=\"gnc164757.html\">Mycobacterium sp. JLS</A></LI>",          // NON
		"<LI><A HREF=\"gnc189918.html\">Mycobacterium sp. KMS</A></LI>",          // NON
		"<LI><A HREF=\"gnc164756.html\">Mycobacterium sp. MCS</A></LI>",          // NON
		"<LI><A HREF=\"gnc515616.html\">Mycobacterium tuberculosis 02_1987</A></LI>",          // NON
		"<LI><A HREF=\"gnc515615.html\">Mycobacterium tuberculosis 94_M4241A</A></LI>",          // NON
		"<LI><A HREF=\"gnc348776.html\">Mycobacterium tuberculosis C</A></LI>",          // NON
		"<LI><A HREF=\"gnc83331.html\">Mycobacterium tuberculosis CDC1551</A></LI>",          // NON
		"<LI><A HREF=\"gnc520140.html\">Mycobacterium tuberculosis EAS054</A></LI>",          // NON
		"<LI><A HREF=\"gnc336982.html\">Mycobacterium tuberculosis F11</A></LI>",          // NON
		"<LI><A HREF=\"gnc537209.html\">Mycobacterium tuberculosis GM 1503</A></LI>",          // NON
		"<LI><A HREF=\"gnc419947.html\">Mycobacterium tuberculosis H37Ra</A></LI>",          // NON
		"<LI><A HREF=\"gnc83332.html\">Mycobacterium tuberculosis H37Rv</A></LI>",          // NON
		"<LI><A HREF=\"gnc478434.html\">Mycobacterium tuberculosis KZN 1435</A></LI>",          // NON
		"<LI><A HREF=\"gnc537210.html\">Mycobacterium tuberculosis T17</A></LI>",          // NON
		"<LI><A HREF=\"gnc520141.html\">Mycobacterium tuberculosis T85</A></LI>",          // NON
		"<LI><A HREF=\"gnc515617.html\">Mycobacterium tuberculosis T92</A></LI>",          // NON
		"<LI><A HREF=\"gnc362242.html\">Mycobacterium ulcerans Agy99</A></LI>",          // NON
		"<LI><A HREF=\"gnc350058.html\">Mycobacterium vanbaalenii PYR-1</A></LI>",          // NON
		"<LI><A HREF=\"gnc2110.html\">Mycoplasma agalactiae</A></LI>",          // NON
		"<LI><A HREF=\"gnc347257.html\">Mycoplasma agalactiae PG2</A></LI>",          // NON
		"<LI><A HREF=\"gnc243272.html\">Mycoplasma arthritidis 158L3-1</A></LI>",          // NON
		"<LI><A HREF=\"gnc340047.html\">Mycoplasma capricolum ATCC 27343</A></LI>",          // NON
		"<LI><A HREF=\"gnc572263.html\">Mycoplasma conjunctivae HRC/581</A></LI>",          // NON
		"<LI><A HREF=\"gnc512564.html\">Mycoplasma crocodyli MP145</A></LI>",          // NON
		"<LI><A HREF=\"gnc710127.html\">Mycoplasma gallisepticum str. R(low)</A></LI>",          // NON
		"<LI><A HREF=\"gnc243273.html\">Mycoplasma genitalium G37</A></LI>",          // NON
		"<LI><A HREF=\"gnc2098.html\">Mycoplasma hominis</A></LI>",          // NON
		"<LI><A HREF=\"gnc295358.html\">Mycoplasma hyopneumoniae 232</A></LI>",          // NON
		"<LI><A HREF=\"gnc262722.html\">Mycoplasma hyopneumoniae 7448</A></LI>",          // NON
		"<LI><A HREF=\"gnc262719.html\">Mycoplasma hyopneumoniae J</A></LI>",          // NON
		"<LI><A HREF=\"gnc267748.html\">Mycoplasma mobile 163K</A></LI>",          // NON
		"<LI><A HREF=\"gnc272632.html\">Mycoplasma mycoides subsp. mycoides SC str. PG1</A></LI>",          // NON
		"<LI><A HREF=\"gnc272633.html\">Mycoplasma penetrans HF-2</A></LI>",          // NON
		"<LI><A HREF=\"gnc272634.html\">Mycoplasma pneumoniae M129</A></LI>",          // NON
		"<LI><A HREF=\"gnc272635.html\">Mycoplasma pulmonis UAB CTIP</A></LI>",          // NON
		"<LI><A HREF=\"gnc262723.html\">Mycoplasma synoviae 53</A></LI>",          // NON
		"<LI><A HREF=\"gnc242231.html\">Neisseria gonorrhoeae FA 1090</A></LI>",         // NON
		"<LI><A HREF=\"gnc521006.html\">Neisseria gonorrhoeae NCCP11945</A></LI>",         // NON
		"<LI><A HREF=\"gnc374833.html\">Neisseria meningitidis 053442</A></LI>",         // NON
		"<LI><A HREF=\"gnc272831.html\">Neisseria meningitidis FAM18</A></LI>",         // NON
		"<LI><A HREF=\"gnc122586.html\">Neisseria meningitidis MC58</A></LI>",         // NON
		"<LI><A HREF=\"gnc122587.html\">Neisseria meningitidis Z2491</A></LI>",         // NON
		"<LI><A HREF=\"gnc662598.html\">Neisseria meningitidis alpha14</A></LI>",         // NON
		"<LI><A HREF=\"gnc434131.html\">Neorickettsia risticii str. Illinois</A></LI>",         // NON
		"<LI><A HREF=\"gnc222891.html\">Neorickettsia sennetsu str. Miyayama</A></LI>",         // NON
		"<LI><A HREF=\"gnc323097.html\">Nitrobacter hamburgensis X14</A></LI>",        // NON
		"<LI><A HREF=\"gnc314253.html\">Nitrobacter sp. Nb-311A</A></LI>",        // NON
		"<LI><A HREF=\"gnc323098.html\">Nitrobacter winogradskyi Nb-255</A></LI>",        // NON
		"<LI><A HREF=\"gnc252305.html\">Oceanicola batsensis HTCC2597</A></LI>",	// NON
		"<LI><A HREF=\"gnc314256.html\">Oceanicola granulosus HTCC2516</A></LI>",	// NON
		"<LI><A HREF=\"gnc338966.html\">Pelobacter propionicus DSM 2379</A></LI>",	// NON
		"<LI><A HREF=\"gnc319225.html\">Pelodictyon luteolum DSM 273</A></LI>",	// NON
		"<LI><A HREF=\"gnc324925.html\">Pelodictyon phaeoclathratiforme BU-1</A></LI>",	// NON
		"<LI><A HREF=\"gnc314280.html\">Photobacterium profundum 3TCK</A></LI>",		//  NON
		"<LI><A HREF=\"gnc298386.html\">Photobacterium profundum SS9</A></LI>",		//  NON
		"<LI><A HREF=\"gnc121723.html\">Photobacterium sp. SKA34</A></LI>",		//  NON
		"<LI><A HREF=\"gnc350703.html\">Pseudomonas aeruginosa 2192</A></LI>",		// NON
		"<LI><A HREF=\"gnc350704.html\">Pseudomonas aeruginosa C3719</A></LI>",		// NON
		"<LI><A HREF=\"gnc557722.html\">Pseudomonas aeruginosa LESB58</A></LI>",		// NON
		"<LI><A HREF=\"gnc381754.html\">Pseudomonas aeruginosa PA7</A></LI>",		// NON
		"<LI><A HREF=\"gnc388272.html\">Pseudomonas aeruginosa PACS2</A></LI>",		// NON
		"<LI><A HREF=\"gnc208964.html\">Pseudomonas aeruginosa PAO1</A></LI>",		// NON
		"<LI><A HREF=\"gnc208963.html\">Pseudomonas aeruginosa UCBPP-PA14</A></LI>",		// NON
		"<LI><A HREF=\"gnc384676.html\">Pseudomonas entomophila L48</A></LI>",		// NON
		"<LI><A HREF=\"gnc220664.html\">Pseudomonas fluorescens Pf-5</A></LI>",		// NON
		"<LI><A HREF=\"gnc205922.html\">Pseudomonas fluorescens Pf0-1</A></LI>",		// NON
		"<LI><A HREF=\"gnc216595.html\">Pseudomonas fluorescens SBW25</A></LI>",		// NON
		"<LI><A HREF=\"gnc399739.html\">Pseudomonas mendocina ymp</A></LI>",		// NON
		"<LI><A HREF=\"gnc351746.html\">Pseudomonas putida F1</A></LI>",		// NON
		"<LI><A HREF=\"gnc76869.html\">Pseudomonas putida GB-1</A></LI>",		// NON
		"<LI><A HREF=\"gnc160488.html\">Pseudomonas putida KT2440</A></LI>",		// NON
		"<LI><A HREF=\"gnc390235.html\">Pseudomonas putida W619</A></LI>",		// NON
		"<LI><A HREF=\"gnc379731.html\">Pseudomonas stutzeri A1501</A></LI>",		// NON
		"<LI><A HREF=\"gnc223283.html\">Pseudomonas syringae</A></LI>",		// NON
		"<LI><A HREF=\"gnc205918.html\">Pseudomonas syringae B728a</A></LI>",		// NON
		"<LI><A HREF=\"gnc264730.html\">Pseudomonas syringae phaseolicola</A></LI>",		// NON
		"<LI><A HREF=\"gnc546231.html\">Pseudomonas syringae pv. tomato T1</A></LI>",		// NON
		"<LI><A HREF=\"gnc259536.html\">Psychrobacter arcticum 273-4</A></LI>",	// NON
		"<LI><A HREF=\"gnc335284.html\">Psychrobacter cryohalolentis K5</A></LI>",	// NON
		"<LI><A HREF=\"gnc349106.html\">Psychrobacter sp. PRwf-1</A></LI>",	// NON
		"<LI><A HREF=\"gnc313595.html\">Psychroflexus torquis ATCC 700755</A></LI>",	// NON
		"<LI><A HREF=\"gnc357804.html\">Psychromonas ingrahamii 37</A></LI>",	// NON
		"<LI><A HREF=\"gnc314282.html\">Psychromonas sp. CNPT3</A></LI>",	// NON
		"<LI><A HREF=\"gnc178306.html\">Pyrobaculum aerophilum str. IM2</A></LI>",		// NON
		"<LI><A HREF=\"gnc340102.html\">Pyrobaculum arsenaticum DSM 13514</A></LI>",		// NON
		"<LI><A HREF=\"gnc410359.html\">Pyrobaculum calidifontis JCM 11548</A></LI>",		// NON
		"<LI><A HREF=\"gnc384616.html\">Pyrobaculum islandicum DSM 4184</A></LI>",		// NON
		"<LI><A HREF=\"gnc272844.html\">Pyrococcus abyssi GE5</A></LI>",		// NON
		"<LI><A HREF=\"gnc186497.html\">Pyrococcus furiosus DSM 3638</A></LI>",		// NON
		"<LI><A HREF=\"gnc70601.html\">Pyrococcus horikoshii OT3</A></LI>",		// NON
		"<LI><A HREF=\"gnc381666.html\">Ralstonia eutropha H16</A></LI>",		// NON
		"<LI><A HREF=\"gnc264198.html\">Ralstonia eutropha JMP134</A></LI>",		// NON
		"<LI><A HREF=\"gnc266264.html\">Ralstonia metallidurans CH34</A></LI>",		// NON
		"<LI><A HREF=\"gnc428406.html\">Ralstonia pickettii 12D</A></LI>",		// NON
		"<LI><A HREF=\"gnc402626.html\">Ralstonia pickettii 12J</A></LI>",		// NON
		"<LI><A HREF=\"gnc267608.html\">Ralstonia solanacearum GMI1000</A></LI>",		// NON
		"<LI><A HREF=\"gnc564066.html\">Ralstonia solanacearum IPO1609</A></LI>",		// NON
		"<LI><A HREF=\"gnc564065.html\">Ralstonia solanacearum MolK2</A></LI>",		// NON
		"<LI><A HREF=\"gnc342110.html\">Ralstonia solanacearum UW551</A></LI>",		// NON
		"<LI><A HREF=\"gnc538025.html\">Rhizobium etli 8C-3</A></LI>",          // NON	
		"<LI><A HREF=\"gnc526949.html\">Rhizobium etli Brasil 5</A></LI>",          // NON
		"<LI><A HREF=\"gnc347834.html\">Rhizobium etli CFN 42</A></LI>",          // NON
		"<LI><A HREF=\"gnc491916.html\">Rhizobium etli CIAT 652</A></LI>",          // NON
		"<LI><A HREF=\"gnc526945.html\">Rhizobium etli CIAT 894</A></LI>",          // NON
		"<LI><A HREF=\"gnc526947.html\">Rhizobium etli GR56</A></LI>",          // NON
		"<LI><A HREF=\"gnc526946.html\">Rhizobium etli IE4771</A></LI>",          // NON
		"<LI><A HREF=\"gnc526950.html\">Rhizobium etli Kim 5</A></LI>",          // NON
		"<LI><A HREF=\"gnc395491.html\">Rhizobium leguminosarum bv. trifolii WSM1325</A></LI>",          // NON
		"<LI><A HREF=\"gnc395492.html\">Rhizobium leguminosarum bv. trifolii WSM2304</A></LI>",          // NON
		"<LI><A HREF=\"gnc216596.html\">Rhizobium leguminosarum bv. viciae 3841</A></LI>",          // NON
		"<LI><A HREF=\"gnc394.html\">Rhizobium sp. NGR234</A></LI>",          // NON
		"<LI><A HREF=\"gnc272943.html\">Rhodobacter sphaeroides 2.4.1</A></LI>",          // NON
		"<LI><A HREF=\"gnc349102.html\">Rhodobacter sphaeroides ATCC 17025</A></LI>",          // NON
		"<LI><A HREF=\"gnc349101.html\">Rhodobacter sphaeroides ATCC 17029</A></LI>",          // NON
		"<LI><A HREF=\"gnc557760.html\">Rhodobacter sphaeroides KD131</A></LI>",          // NON
		"<LI><A HREF=\"gnc314271.html\">Rhodobacterales bacterium HTCC2654</A></LI>",          // NON
		"<LI><A HREF=\"gnc316055.html\">Rhodopseudomonas palustris BisA53</A></LI>",          // NON
		"<LI><A HREF=\"gnc316056.html\">Rhodopseudomonas palustris BisB18</A></LI>",          // NON
		"<LI><A HREF=\"gnc316057.html\">Rhodopseudomonas palustris BisB5</A></LI>",          // NON
		"<LI><A HREF=\"gnc258594.html\">Rhodopseudomonas palustris CGA009</A></LI>",          // NON
		"<LI><A HREF=\"gnc316058.html\">Rhodopseudomonas palustris HaA2</A></LI>",          // NON
		"<LI><A HREF=\"gnc395960.html\">Rhodopseudomonas palustris TIE-1</A></LI>",          // NON
		"<LI><A HREF=\"gnc347255.html\">Rickettsia africae ESF-5</A></LI>",          // NON
		"<LI><A HREF=\"gnc293614.html\">Rickettsia akari str. Hartford</A></LI>",          // NON
		"<LI><A HREF=\"gnc391896.html\">Rickettsia bellii OSU 85-389</A></LI>",          // NON
		"<LI><A HREF=\"gnc336407.html\">Rickettsia bellii RML369-C</A></LI>",          // NON
		"<LI><A HREF=\"gnc293613.html\">Rickettsia canadensis str. McKiel</A></LI>",          // NON
		"<LI><A HREF=\"gnc272944.html\">Rickettsia conorii str. Malish 7</A></LI>",          // NON
		"<LI><A HREF=\"gnc315456.html\">Rickettsia felis URRWXCal2</A></LI>",          // NON
		"<LI><A HREF=\"gnc416276.html\">Rickettsia massiliae MTU5</A></LI>",          // NON
		"<LI><A HREF=\"gnc562019.html\">Rickettsia peacockii str. Rustic</A></LI>",          // NON
		"<LI><A HREF=\"gnc272947.html\">Rickettsia prowazekii str. Madrid E</A></LI>",          // NON
		"<LI><A HREF=\"gnc783.html\">Rickettsia rickettsii</A></LI>",          // NON
		"<LI><A HREF=\"gnc392021.html\">Rickettsia rickettsii str. 'Sheila Smith'</A></LI>",          // NON
		"<LI><A HREF=\"gnc452659.html\">Rickettsia rickettsii str. Iowa</A></LI>",          // NON
		"<LI><A HREF=\"gnc272951.html\">Rickettsia sibirica 246</A></LI>",          // NON
		"<LI><A HREF=\"gnc257363.html\">Rickettsia typhi str. wilmington</A></LI>",          // NON
		"<LI><A HREF=\"gnc59196.html\">Rickettsiella grylli</A></LI>",          // NON
		"<LI><A HREF=\"gnc375451.html\">Roseobacter denitrificans OCh 114</A></LI>",          // NON
		"<LI><A HREF=\"gnc314262.html\">Roseobacter sp. MED193</A></LI>",          // NON
		"<LI><A HREF=\"gnc89187.html\">Roseovarius nubinhibens ISM</A></LI>",          // NON
		"<LI><A HREF=\"gnc314264.html\">Roseovarius sp. 217</A></LI>",          // NON
		"<LI><A HREF=\"gnc314265.html\">Roseovarius sp. HTCC2601</A></LI>",          // NON
		"<LI><A HREF=\"gnc321314.html\">Salmonella enterica Choleraesuis</A></LI>",          // NON
		"<LI><A HREF=\"gnc295319.html\">Salmonella enterica Paratyphi A</A></LI>",          // NON
		"<LI><A HREF=\"gnc41514.html\">Salmonella enterica subsp. arizonae serovar 62:z4,z23:--</A></LI>",          // NON
		"<LI><A HREF=\"gnc440534.html\">Salmonella enterica subsp. enterica serovar 4,[5],12:i:- str. CVM23701</A></LI>",          // NON
		"<LI><A HREF=\"gnc454166.html\">Salmonella enterica subsp. enterica serovar Agona str. SL483</A></LI>",          // NON
		"<LI><A HREF=\"gnc439851.html\">Salmonella enterica subsp. enterica serovar Dublin str. CT_02021853</A></LI>",          // NON
		"<LI><A HREF=\"gnc550537.html\">Salmonella enterica subsp. enterica serovar Enteritidis str. P125109</A></LI>",          // NON
		"<LI><A HREF=\"gnc550538.html\">Salmonella enterica subsp. enterica serovar Gallinarum str. 287/91</A></LI>",          // NON
		"<LI><A HREF=\"gnc454169.html\">Salmonella enterica subsp. enterica serovar Heidelberg str. SL476</A></LI>",          // NON
		"<LI><A HREF=\"gnc439842.html\">Salmonella enterica subsp. enterica serovar Kentucky str. CVM29188</A></LI>",          // NON
		"<LI><A HREF=\"gnc423368.html\">Salmonella enterica subsp. enterica serovar Newport str. SL254</A></LI>",          // NON
		"<LI><A HREF=\"gnc554290.html\">Salmonella enterica subsp. enterica serovar Paratyphi A str. AKU_12601</A></LI>",          // NON
		"<LI><A HREF=\"gnc272994.html\">Salmonella enterica subsp. enterica serovar Paratyphi B str. SPB7</A></LI>",          // NON
		"<LI><A HREF=\"gnc476213.html\">Salmonella enterica subsp. enterica serovar Paratyphi C strain RKS4594</A></LI>",          // NON
		"<LI><A HREF=\"gnc439847.html\">Salmonella enterica subsp. enterica serovar Saintpaul str. SARA29</A></LI>",          // NON
		"<LI><A HREF=\"gnc439843.html\">Salmonella enterica subsp. enterica serovar Schwarzengrund str. CVM19633</A></LI>",          // NON
		"<LI><A HREF=\"gnc497977.html\">Salmonella enterica subsp. enterica serovar Typhi str. 404ty</A></LI>",          // NON
		"<LI><A HREF=\"gnc496065.html\">Salmonella enterica subsp. enterica serovar Typhi str. AG3</A></LI>",          // NON
		"<LI><A HREF=\"gnc220341.html\">Salmonella enterica subsp. enterica serovar Typhi str. CT18</A></LI>",          // NON
		"<LI><A HREF=\"gnc497976.html\">Salmonella enterica subsp. enterica serovar Typhi str. E00-7866</A></LI>",          // NON
		"<LI><A HREF=\"gnc497975.html\">Salmonella enterica subsp. enterica serovar Typhi str. E01-6750</A></LI>",          // NON
		"<LI><A HREF=\"gnc497974.html\">Salmonella enterica subsp. enterica serovar Typhi str. E02-1180</A></LI>",          // NON
		"<LI><A HREF=\"gnc497973.html\">Salmonella enterica subsp. enterica serovar Typhi str. E98-0664</A></LI>",          // NON
		"<LI><A HREF=\"gnc496068.html\">Salmonella enterica subsp. enterica serovar Typhi str. E98-2068</A></LI>",          // NON
		"<LI><A HREF=\"gnc496064.html\">Salmonella enterica subsp. enterica serovar Typhi str. E98-3139</A></LI>",          // NON
		"<LI><A HREF=\"gnc496067.html\">Salmonella enterica subsp. enterica serovar Typhi str. J185</A></LI>",          // NON
		"<LI><A HREF=\"gnc496066.html\">Salmonella enterica subsp. enterica serovar Typhi str. M223</A></LI>",          // NON
		"<LI><A HREF=\"gnc465517.html\">Salmonella enterica subsp. enterica serovar Virchow str. SL491</A></LI>",          // NON
		"<LI><A HREF=\"gnc209261.html\">Salmonella enterica, Typhi Ty2</A></LI>",          // NON
		"<LI><A HREF=\"gnc99287.html\">Salmonella typhimurium LT2</A></LI>",          // NON
		"<LI><A HREF=\"gnc326297.html\">Shewanella amazonensis SB2B</A></LI>",          // NON
		"<LI><A HREF=\"gnc325240.html\">Shewanella baltica OS155</A></LI>",          // NON
		"<LI><A HREF=\"gnc402882.html\">Shewanella baltica OS185</A></LI>",          // NON
		"<LI><A HREF=\"gnc399599.html\">Shewanella baltica OS195</A></LI>",          // NON
		"<LI><A HREF=\"gnc407976.html\">Shewanella baltica OS223</A></LI>",          // NON
		"<LI><A HREF=\"gnc318161.html\">Shewanella denitrificans OS217</A></LI>",          // NON
		"<LI><A HREF=\"gnc318167.html\">Shewanella frigidimarina NCIMB 400</A></LI>",          // NON
		"<LI><A HREF=\"gnc458817.html\">Shewanella halifaxensis HAW-EB4</A></LI>",          // NON
		"<LI><A HREF=\"gnc211586.html\">Shewanella oneidensis MR-1</A></LI>",          // NON
		"<LI><A HREF=\"gnc398579.html\">Shewanella pealeana ATCC 700345</A></LI>",          // NON
		"<LI><A HREF=\"gnc225849.html\">Shewanella piezotolerans WP3</A></LI>",          // NON
		"<LI><A HREF=\"gnc399804.html\">Shewanella putrefaciens 200</A></LI>",          // NON
		"<LI><A HREF=\"gnc319224.html\">Shewanella putrefaciens CN-32</A></LI>",          // NON
		"<LI><A HREF=\"gnc425104.html\">Shewanella sediminis HAW-EB3</A></LI>",          // NON
		"<LI><A HREF=\"gnc94122.html\">Shewanella sp ANA-3</A></LI>",          // NON
		"<LI><A HREF=\"gnc60480.html\">Shewanella sp MR-4</A></LI>",          // NON
		"<LI><A HREF=\"gnc60481.html\">Shewanella sp MR-7</A></LI>",          // NON
		"<LI><A HREF=\"gnc351745.html\">Shewanella sp W3-18-1</A></LI>",          // NON
		"<LI><A HREF=\"gnc637905.html\">Shewanella violacea DSS12</A></LI>",          // NON
		"<LI><A HREF=\"gnc392500.html\">Shewanella woodyi ATCC 51908</A></LI>",          // NON
		"<LI><A HREF=\"gnc344609.html\">Shigella boydii BS512</A></LI>",          // NON
		"<LI><A HREF=\"gnc300268.html\">Shigella boydii Sb227</A></LI>",          // NON
		"<LI><A HREF=\"gnc358708.html\">Shigella dysenteriae 1012</A></LI>",          // NON
		"<LI><A HREF=\"gnc300267.html\">Shigella dysenteriae Sd197</A></LI>",          // NON
		"<LI><A HREF=\"gnc198215.html\">Shigella flexneri 2a str. 2457T</A></LI>",          // NON
		"<LI><A HREF=\"gnc198214.html\">Shigella flexneri 2a str. 301</A></LI>",          // NON
		"<LI><A HREF=\"gnc373384.html\">Shigella flexneri 5 str. 8401</A></LI>",          // NON
		"<LI><A HREF=\"gnc300269.html\">Shigella sonnei Ss046</A></LI>",          // NON
		"<LI><A HREF=\"gnc273036.html\">Staphylococcus aureus RF122</A></LI>",          // NON
		"<LI><A HREF=\"gnc93062.html\">Staphylococcus aureus aureus COL</A></LI>",          // NON
		"<LI><A HREF=\"gnc93061.html\">Staphylococcus aureus aureus NCTC 8325</A></LI>",          // NON
		"<LI><A HREF=\"gnc681288.html\">Staphylococcus aureus subsp. aureus ED98</A></LI>",          // NON
		"<LI><A HREF=\"gnc359787.html\">Staphylococcus aureus subsp. aureus JH1</A></LI>",          // NON
		"<LI><A HREF=\"gnc359786.html\">Staphylococcus aureus subsp. aureus JH9</A></LI>",          // NON
		"<LI><A HREF=\"gnc418127.html\">Staphylococcus aureus subsp. aureus Mu3</A></LI>",          // NON
		"<LI><A HREF=\"gnc451515.html\">Staphylococcus aureus subsp. aureus USA300_FPR3757</A></LI>",          // NON
		"<LI><A HREF=\"gnc451516.html\">Staphylococcus aureus subsp. aureus USA300_TCH1516</A></LI>",          // NON
		"<LI><A HREF=\"gnc546342.html\">Staphylococcus aureus subsp. aureus str. JKD6008</A></LI>",          // NON
		"<LI><A HREF=\"gnc546343.html\">Staphylococcus aureus subsp. aureus str. JKD6009</A></LI>",          // NON
		"<LI><A HREF=\"gnc426430.html\">Staphylococcus aureus subsp. aureus str. Newman</A></LI>",          // NON
		"<LI><A HREF=\"gnc282458.html\">Staphylococcus aureus, MRSA252</A></LI>",          // NON
		"<LI><A HREF=\"gnc282459.html\">Staphylococcus aureus, MRSA476</A></LI>",          // NON
		"<LI><A HREF=\"gnc196620.html\">Staphylococcus aureus, MW2</A></LI>",          // NON
		"<LI><A HREF=\"gnc158878.html\">Staphylococcus aureus, Mu50</A></LI>",          // NON
		"<LI><A HREF=\"gnc158879.html\">Staphylococcus aureus, N315</A></LI>",          // NON
		"<LI><A HREF=\"gnc553212.html\">Staphylococcus capitis SK14</A></LI>",          // NON
		"<LI><A HREF=\"gnc396513.html\">Staphylococcus carnosus subsp. carnosus TM300</A></LI>",          // NON
		"<LI><A HREF=\"gnc176280.html\">Staphylococcus epidermidis</A></LI>",          // NON
		"<LI><A HREF=\"gnc176279.html\">Staphylococcus epidermidis RP62A</A></LI>",          // NON
		"<LI><A HREF=\"gnc279808.html\">Staphylococcus haemolyticus JCSC1435</A></LI>",          // NON
		"<LI><A HREF=\"gnc698737.html\">Staphylococcus lugdunensis HKU09-01</A></LI>",          // NON
		"<LI><A HREF=\"gnc342451.html\">Staphylococcus saprophyticus subsp. saprophyticus ATCC 15305</A></LI>",          // NON
		"<LI><A HREF=\"gnc342613.html\">Streptococcus agalactiae 18RS21</A></LI>",          // NON
		"<LI><A HREF=\"gnc208435.html\">Streptococcus agalactiae 2603V/R</A></LI>",          // NON
		"<LI><A HREF=\"gnc342614.html\">Streptococcus agalactiae 515</A></LI>",          // NON
		"<LI><A HREF=\"gnc205921.html\">Streptococcus agalactiae A909</A></LI>",          // NON
		"<LI><A HREF=\"gnc342617.html\">Streptococcus agalactiae CJB111</A></LI>",          // NON
		"<LI><A HREF=\"gnc342616.html\">Streptococcus agalactiae COH1</A></LI>",          // NON
		"<LI><A HREF=\"gnc342615.html\">Streptococcus agalactiae H36B</A></LI>",          // NON
		"<LI><A HREF=\"gnc211110.html\">Streptococcus agalactiae NEM316</A></LI>",          // NON
		"<LI><A HREF=\"gnc486410.html\">Streptococcus dysgalactiae subsp. equisimilis GGS_124</A></LI>",          // NON
		"<LI><A HREF=\"gnc553482.html\">Streptococcus equi subsp. equi 4047</A></LI>",          // NON
		"<LI><A HREF=\"gnc40041.html\">Streptococcus equi subsp. zooepidemicus</A></LI>",          // NON
		"<LI><A HREF=\"gnc552526.html\">Streptococcus equi subsp. zooepidemicus MGCS10565</A></LI>",          // NON
		"<LI><A HREF=\"gnc637909.html\">Streptococcus gallolyticus UCN34</A></LI>",          // NON
		"<LI><A HREF=\"gnc467705.html\">Streptococcus gordonii str. Challis substr. CH1</A></LI>",          // NON
		"<LI><A HREF=\"gnc365659.html\">Streptococcus mitis B6</A></LI>",          // NON
		"<LI><A HREF=\"gnc511691.html\">Streptococcus mutans NN2025</A></LI>",          // NON
		"<LI><A HREF=\"gnc210007.html\">Streptococcus mutans UA159</A></LI>",          // NON
		"<LI><A HREF=\"gnc488221.html\">Streptococcus pneumoniae 70585</A></LI>",          // NON
		"<LI><A HREF=\"gnc561276.html\">Streptococcus pneumoniae ATCC 700669</A></LI>",          // NON
		"<LI><A HREF=\"gnc516950.html\">Streptococcus pneumoniae CGSP14</A></LI>",          // NON
		"<LI><A HREF=\"gnc373153.html\">Streptococcus pneumoniae D39</A></LI>",          // NON
		"<LI><A HREF=\"gnc512566.html\">Streptococcus pneumoniae G54</A></LI>",          // NON
		"<LI><A HREF=\"gnc487214.html\">Streptococcus pneumoniae Hungary19A-6</A></LI>",          // NON
		"<LI><A HREF=\"gnc488222.html\">Streptococcus pneumoniae JJA</A></LI>",          // NON
		"<LI><A HREF=\"gnc488223.html\">Streptococcus pneumoniae P1031</A></LI>",          // NON
		"<LI><A HREF=\"gnc171101.html\">Streptococcus pneumoniae R6</A></LI>",          // NON
		"<LI><A HREF=\"gnc170187.html\">Streptococcus pneumoniae TIGR4</A></LI>",          // NON
		"<LI><A HREF=\"gnc487213.html\">Streptococcus pneumoniae Taiwan19F-14</A></LI>",          // NON
		"<LI><A HREF=\"gnc160490.html\">Streptococcus pyogenes M1 GAS</A></LI>",          // NON
		"<LI><A HREF=\"gnc294934.html\">Streptococcus pyogenes M49 591</A></LI>",          // NON
		"<LI><A HREF=\"gnc370552.html\">Streptococcus pyogenes MGAS10270</A></LI>",          // NON
		"<LI><A HREF=\"gnc286636.html\">Streptococcus pyogenes MGAS10394</A></LI>",          // NON
		"<LI><A HREF=\"gnc370554.html\">Streptococcus pyogenes MGAS10750</A></LI>",          // NON
		"<LI><A HREF=\"gnc370553.html\">Streptococcus pyogenes MGAS2096</A></LI>",          // NON
		"<LI><A HREF=\"gnc198466.html\">Streptococcus pyogenes MGAS315</A></LI>",          // NON
		"<LI><A HREF=\"gnc293653.html\">Streptococcus pyogenes MGAS5005</A></LI>",          // NON
		"<LI><A HREF=\"gnc319701.html\">Streptococcus pyogenes MGAS6180</A></LI>",          // NON
		"<LI><A HREF=\"gnc186103.html\">Streptococcus pyogenes MGAS8232</A></LI>",          // NON
		"<LI><A HREF=\"gnc370551.html\">Streptococcus pyogenes MGAS9429</A></LI>",          // NON
		"<LI><A HREF=\"gnc471876.html\">Streptococcus pyogenes NZ131</A></LI>",          // NON
		"<LI><A HREF=\"gnc193567.html\">Streptococcus pyogenes SSI-1</A></LI>",          // NON
		"<LI><A HREF=\"gnc160491.html\">Streptococcus pyogenes str. Manfredo</A></LI>",          // NON
		"<LI><A HREF=\"gnc388919.html\">Streptococcus sanguinis SK36</A></LI>",          // NON
		"<LI><A HREF=\"gnc391295.html\">Streptococcus suis 05ZYH33</A></LI>",          // NON
		"<LI><A HREF=\"gnc391296.html\">Streptococcus suis 98HAH33</A></LI>",          // NON
		"<LI><A HREF=\"gnc568814.html\">Streptococcus suis BM407</A></LI>",          // NON
		"<LI><A HREF=\"gnc218494.html\">Streptococcus suis P1/7</A></LI>",          // NON
		"<LI><A HREF=\"gnc568813.html\">Streptococcus suis SC84</A></LI>",          // NON
		"<LI><A HREF=\"gnc299768.html\">Streptococcus thermophilus CNRZ1066</A></LI>",          // NON
		"<LI><A HREF=\"gnc322159.html\">Streptococcus thermophilus LMD-9</A></LI>",          // NON
		"<LI><A HREF=\"gnc264199.html\">Streptococcus thermophilus LMG 18311</A></LI>",          // NON
		"<LI><A HREF=\"gnc218495.html\">Streptococcus uberis 0140J</A></LI>",          // NON
		"<LI><A HREF=\"gnc227882.html\">Streptomyces avermitilis MA-4680</A></LI>",          // NON
		"<LI><A HREF=\"gnc100226.html\">Streptomyces coelicolor A3(2)</A></LI>",          // NON
		"<LI><A HREF=\"gnc455632.html\">Streptomyces griseus subsp. griseus NBRC 13350</A></LI>",          // NON
		"<LI><A HREF=\"gnc680198.html\">Streptomyces scabiei 87.22</A></LI>",          // NON
		"<LI><A HREF=\"gnc330779.html\">Sulfolobus acidocaldarius DSM 639</A></LI>",          // NON
		"<LI><A HREF=\"gnc425944.html\">Sulfolobus islandicus L.D.8.5</A></LI>",          // NON
		"<LI><A HREF=\"gnc429572.html\">Sulfolobus islandicus L.S.2.15</A></LI>",          // NON
		"<LI><A HREF=\"gnc427317.html\">Sulfolobus islandicus M.14.25</A></LI>",          // NON
		"<LI><A HREF=\"gnc427318.html\">Sulfolobus islandicus M.16.27</A></LI>",          // NON
		"<LI><A HREF=\"gnc426118.html\">Sulfolobus islandicus M.16.4</A></LI>",          // NON
		"<LI><A HREF=\"gnc439386.html\">Sulfolobus islandicus Y.G.57.14</A></LI>",          // NON
		"<LI><A HREF=\"gnc419942.html\">Sulfolobus islandicus Y.N.15.51</A></LI>",          // NON
		"<LI><A HREF=\"gnc273057.html\">Sulfolobus solfataricus P2</A></LI>",          // NON
		"<LI><A HREF=\"gnc273063.html\">Sulfolobus tokodaii str. 7</A></LI>",          // NON
		"<LI><A HREF=\"gnc525903.html\">Thermanaerovibrio acidaminovorans DSM 6589</A></LI>",		// NON
		"<LI><A HREF=\"gnc340099.html\">Thermoanaerobacter ethanolicus ATCC 33223</A></LI>",		// NON
		"<LI><A HREF=\"gnc399726.html\">Thermoanaerobacter ethanolicus X514</A></LI>",		// NON
		"<LI><A HREF=\"gnc580331.html\">Thermoanaerobacter italicus Ab9</A></LI>",		// NON
		"<LI><A HREF=\"gnc273068.html\">Thermoanaerobacter tengcongensis MB4</A></LI>",		// NON
		"<LI><A HREF=\"gnc525904.html\">Thermobaculum terrenum ATCC BAA-798</A></LI>",		// NON
		"<LI><A HREF=\"gnc593117.html\">Thermococcus gammatolerans EJ3</A></LI>",		// NON
		"<LI><A HREF=\"gnc69014.html\">Thermococcus kodakaraensis KOD1</A></LI>",		// NON
		"<LI><A HREF=\"gnc523850.html\">Thermococcus onnurineus NA1</A></LI>",		// NON
		"<LI><A HREF=\"gnc604354.html\">Thermococcus sibiricus MM 739</A></LI>",		// NON
		"<LI><A HREF=\"gnc368408.html\">Thermofilum pendens Hrk 5</A></LI>",		// NON
		"<LI><A HREF=\"gnc416591.html\">Thermotoga lettingae TMO</A></LI>",		// NON
		"<LI><A HREF=\"gnc243274.html\">Thermotoga maritima MSB8</A></LI>",		// NON
		"<LI><A HREF=\"gnc590168.html\">Thermotoga naphthophila RKU-10</A></LI>",		// NON
		"<LI><A HREF=\"gnc309803.html\">Thermotoga neapolitana DSM 4359</A></LI>",		// NON
		"<LI><A HREF=\"gnc390874.html\">Thermotoga petrophila RKU-1</A></LI>",		// NON
		"<LI><A HREF=\"gnc126740.html\">Thermotoga sp. RQ2</A></LI>",		// NON
		"<LI><A HREF=\"gnc521045.html\">Thermotogales bacterium TBF 19.5.1</A></LI>",		// NON
		"<LI><A HREF=\"gnc498848.html\">Thermus aquaticus Y51MC23</A></LI>",		// NON
		"<LI><A HREF=\"gnc262724.html\">Thermus thermophilus HB27</A></LI>",		// NON
		"<LI><A HREF=\"gnc300852.html\">Thermus thermophilus HB8</A></LI>",		// NON
		"<LI><A HREF=\"gnc505682.html\">Ureaplasma parvum serovar 3 str. ATCC 27815</A></LI>",		// NON
		"<LI><A HREF=\"gnc273119.html\">Ureaplasma parvum serovar 3 str. ATCC 700970</A></LI>",		// NON
		"<LI><A HREF=\"gnc565575.html\">Ureaplasma urealyticum serovar 10 str. ATCC 33699</A></LI>",		// NON
		"<LI><A HREF=\"gnc550748.html\">Ureaplasma urealyticum serovar 4 str. ATCC 27816</A></LI>",		// NON
		"<LI><A HREF=\"gnc550773.html\">Ureaplasma urealyticum serovar 9 str. ATCC 33175</A></LI>",		// NON
		"<LI><A HREF=\"gnc314288.html\">Vibrio alginolyticus 12G01</A></LI>",		// NON
		"<LI><A HREF=\"gnc314292.html\">Vibrio angustum S14</A></LI>",		// NON
		"<LI><A HREF=\"gnc412614.html\">Vibrio cholerae 2740-80</A></LI>",		// NON
		"<LI><A HREF=\"gnc579112.html\">Vibrio cholerae M66-2</A></LI>",		// NON
		"<LI><A HREF=\"gnc593588.html\">Vibrio cholerae MJ-1236</A></LI>",		// NON
		"<LI><A HREF=\"gnc345072.html\">Vibrio cholerae MO10</A></LI>",		// NON
		"<LI><A HREF=\"gnc243277.html\">Vibrio cholerae O1 biovar eltor str. N16961</A></LI>",		// NON
		"<LI><A HREF=\"gnc345073.html\">Vibrio cholerae O395</A></LI>",		// NON
		"<LI><A HREF=\"gnc345074.html\">Vibrio cholerae RC385</A></LI>",		// NON
		"<LI><A HREF=\"gnc345075.html\">Vibrio cholerae V51</A></LI>",		// NON
		"<LI><A HREF=\"gnc345076.html\">Vibrio cholerae V52</A></LI>",		// NON
		"<LI><A HREF=\"gnc312309.html\">Vibrio fischeri ES114</A></LI>",		// NON
		"<LI><A HREF=\"gnc388396.html\">Vibrio fischeri MJ11</A></LI>",		// NON
		"<LI><A HREF=\"gnc338187.html\">Vibrio harveyi ATCC BAA-1116</A></LI>",		// NON
		"<LI><A HREF=\"gnc223926.html\">Vibrio parahaemolyticus RIMD 2210633</A></LI>",		// NON
		"<LI><A HREF=\"gnc316275.html\">Vibrio salmonicida LFI1238</A></LI>",		// NON
		"<LI><A HREF=\"gnc150340.html\">Vibrio sp. Ex25</A></LI>",		// NON
		"<LI><A HREF=\"gnc314290.html\">Vibrio sp. MED222</A></LI>",		// NON
		"<LI><A HREF=\"gnc314291.html\">Vibrio splendidus 12B01</A></LI>",		// NON
		"<LI><A HREF=\"gnc575788.html\">Vibrio splendidus LGP32</A></LI>",		// NON
		"<LI><A HREF=\"gnc216895.html\">Vibrio vulnificus CMCP6</A></LI>",		// NON
		"<LI><A HREF=\"gnc196600.html\">Vibrio vulnificus YJ016</A></LI>",		// NON
		"<LI><A HREF=\"gnc29447.html\">Xanthomonas albilineans</A></LI>",		// NON
		"<LI><A HREF=\"gnc190486.html\">Xanthomonas axonopodis</A></LI>",		// NON
		"<LI><A HREF=\"gnc190485.html\">Xanthomonas campestris ATCC 33913</A></LI>",		// NON
		"<LI><A HREF=\"gnc509169.html\">Xanthomonas campestris pv. campestris str. B100</A></LI>",		// NON
		"<LI><A HREF=\"gnc316273.html\">Xanthomonas campestris vesicatoria 85-10</A></LI>",		// NON
		"<LI><A HREF=\"gnc314565.html\">Xanthomonas campestris, 8004</A></LI>",		// NON
		"<LI><A HREF=\"gnc342109.html\">Xanthomonas oryzae oryzae MAFF 311018</A></LI>",		// NON
		"<LI><A HREF=\"gnc291331.html\">Xanthomonas oryzae pv. oryzae KACC10331</A></LI>",		// NON
		"<LI><A HREF=\"gnc360094.html\">Xanthomonas oryzae pv. oryzae PXO99A</A></LI>",		// NON
		"<LI><A HREF=\"gnc349968.html\">Yersinia bercovieri ATCC 43970</A></LI>",		// NON
		"<LI><A HREF=\"gnc393305.html\">Yersinia enterocolitica subsp. enterocolitica 8081</A></LI>",		// NON
		"<LI><A HREF=\"gnc349966.html\">Yersinia frederiksenii ATCC 33641</A></LI>",		// NON
		"<LI><A HREF=\"gnc349965.html\">Yersinia intermedia ATCC 29909</A></LI>",		// NON
		"<LI><A HREF=\"gnc349967.html\">Yersinia mollaretii ATCC 43969</A></LI>",		// NON
		"<LI><A HREF=\"gnc349746.html\">Yersinia pestis Angola</A></LI>",		// NON
		"<LI><A HREF=\"gnc360102.html\">Yersinia pestis Antiqua</A></LI>",		// NON
		"<LI><A HREF=\"gnc412420.html\">Yersinia pestis CA88-4125</A></LI>",		// NON
		"<LI><A HREF=\"gnc214092.html\">Yersinia pestis CO92</A></LI>",		// NON
		"<LI><A HREF=\"gnc187410.html\">Yersinia pestis KIM</A></LI>",		// NON
		"<LI><A HREF=\"gnc377628.html\">Yersinia pestis Nepal516</A></LI>",		// NON
		"<LI><A HREF=\"gnc386656.html\">Yersinia pestis Pestoides F</A></LI>",		// NON
		"<LI><A HREF=\"gnc637386.html\">Yersinia pestis Z176003</A></LI>",		// NON
		"<LI><A HREF=\"gnc229193.html\">Yersinia pestis biovar Medievalis 91001</A></LI>",		// NON
		"<LI><A HREF=\"gnc349747.html\">Yersinia pseudotuberculosis IP 31758</A></LI>",		// NON
		"<LI><A HREF=\"gnc273123.html\">Yersinia pseudotuberculosis IP 32953</A></LI>",		// NON
		"<LI><A HREF=\"gnc502801.html\">Yersinia pseudotuberculosis PB1/+</A></LI>",		// NON
		"<LI><A HREF=\"gnc502800.html\">Yersinia pseudotuberculosis YPIII</A></LI>",		// NON
		"<LI><A HREF=\"gnc655815.html\">Zunongwangia profunda SM-A87</A></LI>",		// NON
		"<LI><A HREF=\"gnc622759.html\">Zymomonas mobilis subsp. mobilis NCIB 11163</A></LI>",		// NON
		"<LI><A HREF=\"gnc264203.html\">Zymomonas mobilis subsp. mobilis ZM4</A></LI>"		// NON
	};
}
